### ISSUE TITLE
Add NullHandlers or not?

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#1186]
The current master branch does not have any NullHandlers.

See the (merged) PR #1169 for discussion items.

**Comment by KSchopmeyer** [comment]
The question is whether my code that simply does not call the loggers is enough or we need to set NullLoggers for any that we do not use. 

I am conflicted right now but the current code does work for us. I propose we release as is and if we sort out issues we add NullHandlers.  That is opinion only but it is before noon so maybe partly rational.

**Comment by KSchopmeyer** [comment]
My tendency right now is release as is since this is experimental.

**Comment by andy-maier** [comment]
I did some more experiments, and found:
1. My understanding that the existence of a handler on a logger would prevent the upwards propagation was incorrect. I don't know where I got that from. Instead, what prevents upwards propagation is the "propagate" attribute on a logger being False and the level of a logger being more restricted than the log event. The [Logging Flow](https://docs.python.org/2/howto/logging.html#logging-flow) also makes that clear.
2. Having a NullHandler on a logger is still recommended in [Configuring logging for a library](https://docs.python.org/2/howto/logging.html#configuring-logging-for-a-library) and in several blog entries, but for a different reason: It suppresses the warning "No handlers could be found for logger ...". I have verified that that warning is only issued on Python 2, but not on Python 3 (at least not on 3.4+). Yet, the [Configuring logging for a library (py36)](https://docs.python.org/3.6/howto/logging.html#configuring-logging-for-a-library) still recommends adding a NullHandler to a library.

So having or not having a NullHandler is just related to whether or not that warning should be suppressed. I suggest adding a NullHandler on Python 2.

The other thing is, that in our config functions, when we add a handler that actually emits the log records to the "pywbem.<xxx>" loggers, this also does not prevent the log event from propagating up. So a root logger that is configured to output DEBUG level would also output our logs, even when the pywbem handler already outputs them. To prevent that, we could for example set the "propagate" attribute of the logger that has a handler active, to False. If we do that, then we should probably have a log config function that disables the logging. Right now, our log config functions can only be used to enable logging, or to not change logging, but not to disable logging.

**Comment by andy-maier** [comment]
On releasing as experimental: That is true, but it is also true that we are currently redesigning it, so this is already the second attempt of an experimental logging functionality. I don't want to put a third exterimental attempt on, if I can avoid it.

**Comment by andy-maier** [comment]
I have put up PR #1190 which adds NullHandler to the pywbem logger on Python 2.
It does not change anything on the propagation, that part is still a discussion point.

**Comment by KSchopmeyer** [comment]
My understanding that the existence of a handler on a logger would prevent the upwards propagation was incorrect. I don't know where I got that from. Instead, what prevents upwards propagation is the "propagate" attribute on a logger being False and the level of a logger being more restricted than the log event. The Logging Flow also makes that clear.

I also misinterpreted this one.

What behavior do we want. Here are 3 use cases:

1. No loggers but ours. User does not set things like basicconfig just uses our logger calls.
In this case, the log output is totally controlled by our configure_logger().

2. User wants to set a general set of logs for their app but wants separate control for pywbem logs. They set a log level above us (i.e. a root logger) but do not expect our logs to show up in the output from that root logger definition.

In this case they define our loggers detail_level and log_dest or user defines logger at 'pywbem' level which outputs for DEBUG. This enables log output for our logs which enables them but then the pywbem level logger (or the api and http loggers) should also stop propagation so that our log output gets generated at the level of 'pywbem' and below and not propagated.

3. User wants to use some standard log config above pywbem but include pywbem  logs in the result when the higher level is DEBUG

They need to set the detail_level but not the loggers or prevent upward propagation. Note that since not setting a particular detail_level prevents our logs from being created, the user can still control which loggers are active and what detail they output. Thus our log requests get propagated upward and displayed if the DEBUG level is set in the hiearchy.  Not sure that this is what we really want since, in general we know that our loggers use a lot of cpu and we really want people to enable them only when they are needed, not in general.  However, since we only create logs when the logger is at the DEBUG level, I assume we are fairly protected.

4. User wants to control all logs through a logger configuration.  Here we have a problem because of the detail_level we define.  The configure file concept makes it really difficult since our detail_level actually controls a lot but is not part of standard log config files.  This is a TODO right now.

I am not following you logic about disabling logging but I may be missing something.  However, it would appear that we may need control over upward propagation. But then if they set log_dest and create a logger, can we assume that there should be no propagation and only if they do not define a log_dest do we always assume that they want to propagate upward.

Think this over.  Does it mean that what we should do is to always set the no-propagation flag when we create one of our loggers??? Thus, if we output the log, we do not pass it up the hiearchy.

By the way, another possible complexity.  set_level operates in two places, on the logger and on the handler.  If it is set on the handler, that is a second filter.  If not set, there is no filtering by the handler. The one in the handler allows different handlers to output at different levels for the same logger.

**Comment by andy-maier** [comment]
The logic about disabling is that if we prevent upward propagation when enabling, this is such a significant change in the logging setup, that we ought to have a way to undo that.

**Comment by KSchopmeyer** [comment]
How about if we add a propagation parameter for each log type.  Default no propagate but if propagate=True it propagates upward?  Instead of disabling they can determine whether they want to propagate upward in configure_logger.  I would not propose that for the string form at this point since we are seeing that as a cli tool and do not expect much on top if it.

**Comment by andy-maier** [comment]
Probably a good idea. I'll prepare a PR for that.

**Comment by andy-maier** [comment]
I have put up PR #1194, for review.
