### ISSUE TITLE
Need universal cmd line way to get pywbem version

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1244]
At least one (Cassius Concepcion) user with wide distribution of pywbem usage and installations over wide set of tools (yum, rpm, pip, etc.) needs a way to get the pywbem version from the various installations preferably a cmd line way.

Since we only added the --version option to wbemcli as of pywbem 0.11.0, that is not universal as a cmdline mechanism.

They cannot depend on things like pip list exclusively because not all installations were piped. Nor can they depend on a single installation tool since there are many variations in the tools used and in trying to get version information out of these installations.

They are looking first for suggestions.

**Comment by andy-maier** [comment]
The following approach should work with all pywbem versions that were ever released to Pypi:
```
$ python -c "import pywbem; print(pywbem.__version__)"
0.12.1.dev22
```

**Comment by cassin88** [comment]
Most of the systems are running 0.70 – 0.10 and we can’t easily upgrade to newer version because it’s in production now.  Most if not all of them are running behind a firewall.  python -c "import pywbem; print(pywbem.__version__)" appeared to error out in versions earlier than 0.10

**Comment by andy-maier** [comment]
I have to correct myself regarding the version from which on this works: The `__version__` attribute was introduced in pywbem 0.8.1.

I verified that the released packages for 0.8.1, 0.9.0, 0.10.0 do report the version that way.

Make sure that the Python environment in which you execute the command is the same as where you run the applications using pywbem. Note that Python includes the current directory in the module search path, so it may use a possibly present `pywbem` package directory instead of an installed version. You can print the `__file__` attribute to verify where the package was loaded from, in the Python environment you are using (a virtualenv in my case):

```
$ pip install pywbem==0.8.1
Collecting pywbem==0.8.1
Requirement already satisfied: six in /Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages (from pywbem==0.8.1) (1.11.0)
Requirement already satisfied: M2Crypto in /Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages (from pywbem==0.8.1) (0.29.0)
Requirement already satisfied: ply in /Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages (from pywbem==0.8.1) (3.11)
Requirement already satisfied: typing in /Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages (from M2Crypto->pywbem==0.8.1) (3.6.4)
Installing collected packages: pywbem
  Found existing installation: pywbem 0.10.0
    Uninstalling pywbem-0.10.0:
      Successfully uninstalled pywbem-0.10.0
Successfully installed pywbem-0.8.1
$ python -c "import pywbem; print(pywbem.__version__)"
0.8.1
$ python -c "import pywbem; print(pywbem.__file__)"
/Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages/pywbem/__init__.pyc
```

If it still does not print the `__version__` attribute, can you please post the error result?

**Comment by andy-maier** [comment]
With pywbem 0.7.0, the following works to display the version. This does no longer work from 0.8.1 on:

```
$ pip install pywbem==0.7.0
Collecting pywbem==0.7.0
Installing collected packages: pywbem
  Found existing installation: pywbem 0.8.1
    Uninstalling pywbem-0.8.1:
      Successfully uninstalled pywbem-0.8.1
Successfully installed pywbem-0.7.0
$ python $(dirname $(python -c "import pywbem; print(pywbem.__file__)"))/setup.py --version
0.7.0
```

**Comment by andy-maier** [comment]
Please let us know whether this addresses your need.

**Comment by cassin88** [comment]
I'm unable to get consistent result.  Here's one system where pywbem was installed using "yum".

# rpm -qa |grep pywbem
pywbem-0.7.0-4.el6.noarch
#
# python -c "import pywbem; print(pywbem.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute '__version__'
#
# python $(dirname $(python -c "import pywbem; print(pywbem.__file__)"))/setup.py --version
python: can't open file '/usr/lib/python2.6/site-packages/pywbem/setup.py': [Errno 2] No such file or directory
#

**Comment by andy-maier** [comment]
Cassius, ok I did not know that. Thanks for providing this case.

BTW, the attribute for the version is `pywbem.__version__`, not `pywbem.version`. But 0.7.0 has neither of them.

Since 0.7.0 is the only version released to Pypi without a `__version__` attribute, and most likely the only version without that attribute that was packaged into Linux distros, I think it is fair to assume that the version is 0.7.0 if the `__version__` attribute is missing.

I have come up with this shell command that does that and that brings the whole logic together into one command:

```
python -c "import pywbem; v=getattr(pywbem, '__version__', '0.7.0'); print(v)"
```

**Comment by cassin88** [comment]
Hi Andy, I have tried it on 0.7.0 and 0.10.0.  Both gave consistent result.  Good job!

Thank you very much.

**Comment by andy-maier** [comment]
Good to hear! I'll close this issue. Feel free to reopen it if it does not work in some environment. We'll describe this in the documentation soon, see issue #1246.
