### ISSUE TITLE
cim_obj copy methods do not create completely new objects

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1251]
I had problem in the following code in the mock:

cc = [class in repo].copy()  # trying to create copy of class in repo to return for GetClass

When I try to remove the qualifiers from the properties in copied class (cc) It actually removes them from the properties in the class in the repo.

The following code change fixed the issue. Changed the copy of the properties, methods, and
qualifiers NocaseDict to do a deepcopy.  I am not saying that this is the correct solution but it does fix the issue where what was in the copied class was references to the original <classinrepo> qualifiers

    def copy(self):
        """
        Return a copy of the :class:`~pywbem.CIMClass` object.
        """
        result = CIMClass(self.classname)
        result.properties = deepcopy(self.properties)
        result.methods = deepcopy(self.methods)
        result.superclass = self.superclass
        result.qualifiers = deepcopy(self.qualifiers)
        result.path = None if self.path is None else self.path.copy()

**Comment by andy-maier** [comment]
The copy methods are supposed to create deep copies, IMO, so this is rightfully qualified as a bug.

**Comment by KSchopmeyer** [comment]
I made one change just to use deepcopy just to confirm that it fixes the problem but we need to sort out what is the best for us, a deep copy or just an iterative copy of those things that are lists, dictionaries, etc.

**Comment by andy-maier** [comment]
If we just look at NocaseDict at the moment, then what it does in its copy() method is a middle-deep copy: It does make a shallow copy of the OrderedDict it maintains, so this is more deep than shallow for the OncaseDict object, but also not a completely deep copy.

I verified that the testcases we have on test_nocasedict.py fail for the copy() method when we change the middle-deep implementation to a completely shallow implementation.

I also verified that the copy.copy() and copy.deepcopy() methods work on NocaseDict and on the CIM objects, and that is what a user should actually use, because then they have control over shallow vs. deep.

The question is what do we do with the copy() method on NocaseDict and on these CIM objects.

Given that copy() is a standard method on dicts, that is described as a shallow copy, I lean towards changing it to shallow as well, but that would be an incompatible change to some usages (e.g. to our current testcases).

**Comment by KSchopmeyer** [comment]
Discussion.  Proposed best solution among.  I will be glad to make the changes.

**Comment by andy-maier** [comment]
We agreed that the copy() methods should continue making middle-deep copies, that this behavior should be documented, and that a note hinting at copy.copy() and copy.deepcopy() should be added.

This is addressed by PR #1255.

The mock code that discovered this should be changed to use copy.deepcopy().
