### ISSUE TITLE
Method from_instances allows Null values in CIMInstanceName

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1298]
We do not test for None in key properties when build the instance path from the instance.

DSP0004 states that key properties should not be None.

Suggest adding test to confirm property value is not None and raise error if it is None.

**Comment by KSchopmeyer** [comment]
Discussion: Andy, do you agree?

**Comment by andy-maier** [comment]
If we add such a checking, why would we only add it for `from_instance()` but not also for the normal `CIMInstanceName` object construction (which is by the way also used within `from_instance()`)?

If we agree to add it consistently, the right place would probably be `CIMInstanceName._cim_keybinding()` or the setter method of `CIMInstanceName.keybindings`.

Because this is an incompatible change for users, I suggest adding a config variable that allows changing back to the current behavior.

**Comment by KSchopmeyer** [comment]
Sounds logical.

**Comment by andy-maier** [comment]
Ok, then we have a direction for this one.

**Comment by KSchopmeyer** [comment]
We agreed that disallowing NUll is the default behavior
