### ISSUE TITLE
MOFParseError does not have attributes for line/column in error

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#169]
See PR # 423
The `MOFParseError` exception class is a subclass of `ValueError` and does not provide any additional attributes.
- It would be good if it indicated the line and column numbers of the problem it communicates. And the file name.
- Also, it is somehow strange to see it derived from `ValueError`. Ideas for different classes, or reminders on why it needs to be that way, are welcome.

**Comment by KSchopmeyer** [comment]
Note, however, that when it displays an error it puts the line with the error and then another line with a ^ at the position of the error.  However, It would be better to actually do some format that editors can handle to get the user back to the error itself.

**Comment by andy-maier** [comment]
That's fine for a user of the command line script. But if we also want to support programmatic callers of the API well, then the MOFParseError exception is probably a better interface for them compared to having their own logger and parsing what's printed on it (including anything that is not a syntax error at all).

**Comment by KSchopmeyer** [comment]
Interesting. Note that tools like pylint do both. Which was one of the things that was causing issues with my pylint.awk program but which geany handles just fine.

**Comment by KSchopmeyer** [comment]
Propose we follow the pylint model.

**Comment by andy-maier** [comment]
I'm not arguing against logging the syntax errors, I just think we need the exception based interface in addition. After all, the exception is thrown, it has just no meaningful information inside.

**Comment by andy-maier** [comment]
We agreed to have the information in the exception object.
In addition, the pylint comment by Karl means that the log messages should be in pylint standard format which can be understood by some editors (such as geany)

**Comment by KSchopmeyer** [comment]
Andy. Maybe I am confused but MOFParseError subclasses from exceptions.py.Error which is the base for pywbem and subclasses from Exception.  MOFParseError does not subclass from Value.
In fact, MOFParseError takes line and file information directly from ply yacc in the p_error(p) function when called from ply.  It gets file name, line number, line position,  and context(i.e. that line) from the parser in p_error and stuffs them into MOFParseError instance.

One issue is that it does not get this correctly when called from elsewhere (i.e from a mof_production)  because for whatever the reason, when you use the p parameter that is part of the mof_compiler definition of the parser, not all of the same functionality is visible.  Means digging further into the parser to find out why.  Once we are getting the same information universally and using the same exception for all mof_errors, we can generalize the result.  See the issue #204 where we proposed a second exception class.

**Comment by andy-maier** [comment]
Karl, in branch stable_0.8, MOFParseError derives from ValueError. So in master, that must have been fixed at some point. Did not research when.

Line/File info: Let's figure out how that can be obtained for all cases, including the new semantic errors.

**Comment by KSchopmeyer** [comment]
That is what is best I think.  I will also research where we modified 
this to have the hiearchy

   Exception->Error->MOFParseError

since I did not realize that this must have been a 0.9.0 change.


On 05/16/2016 10:52 AM, Andreas Maier wrote:
>
> Karl, in branch stable_0.8, MOFParseError derives from ValueError. So 
> in master, that must have been fixed at some point. Did not research when.
>
> Line/File info: Let's figure out how that can be obtained for all 
> cases, including the new semantic errors.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/pywbem/pywbem/issues/169#issuecomment-219462578>
>


-- 
================
Karl Schopmeyer
email: k.schopmeyer@swbell.net, k.schopmeyer@opengroup.org
tel: 972-814-5581

**Comment by andy-maier** [comment]
Was fixed in PR #423. Closing this issue.
