### ISSUE TITLE
Why can't the result of IterQueryInstances be iterable?

### ISSUE THREAD

**Issue by tanshaolong** [pywbem/pywbem#1741]
Hi

I am trying IterQueryInstances() to query storage volumes. I refer the doc https://nbviewer.jupyter.org/github/pywbem/pywbem/blob/master/docs/notebooks/iterablecimoperations.ipynb#IterQueryInstances as sample, but I get “TypeError: 'IterQueryInstancesReturn' object is not iterable” error message.

The below is some detail for my test.
```
query = 'Select * from IBMTSSVC_StorageVolume'
query_language = ‘WQL’
max_obj_cnt = 10
inst_iterator = conn.IterQueryInstances(query_language, query,MaxObjectCount=max_obj_cnt)
2019-04-23 22:25:23,175-pywbem.api.4-11704-Request:4-11704 ExecQuery(Query='Select * from IBMTSSVC_StorageVolume', QueryLanguage='WQL', namespace=None)
2019-04-23 22:25:25,123-pywbem.api.4-11704-Return:4-11704 ExecQuery(list of CIMInstance; count=34)

for inst in inst_iterator:
   print(inst.tomof())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'IterQueryInstancesReturn' object is not iterable

type(inst_iterator)
<class 'pywbem.cim_operations.IterQueryInstancesReturn'>
```

Because I open the pywbem log, we can clearly see IterQueryInstances execute “ExecQuery”and get 34 volumes result. Why can’t we be iterable the result? Thank you.

Also, would you give some reference for WQL syntax? Thank you.

Best regards
Ray

**Comment by KSchopmeyer** [comment]
Let me look into the IterQueryInstances before I answer but for the Query languages:

1. The officially supported query language from DMTF is really CQL and that is documented in the DMTF specification DSP0202.  However, nobody ever implemented all of it, in particular the joins component.

2. WQL was an early query language with specifications (never even formally released) from Microsoft but never had a specification from the DMTF.  We all found later that many of us were working to different versions of the WQL specification so sadly, there are weird variations between different implementations of the language.  At the same time, the majority of WQL implementations are very close to one another differing primarily in boundary cases.  OpenPegasus supports both WQL and CQL.

Note that the pull operations (and therefore the iter operations iterenumerateinstances, iterassociator, iterreferences support a more simplistic language FQL (see DMTF specification DSP 0212) that can filter responses based largely on a simplified where clause that allows filitering by property data for instances being returned (ex. propertyx > 3, etc.

I will track down the WQL definition we used for OpenPegasus and get back to you.

**Comment by KSchopmeyer** [comment]
Whoops.  Error in the Notebook.  The return from the IterQueryInstances contains two components, 

1. query_result_class

2. generator

This is because in the pull operations, (we) added the optional ability to return a pseudo class representing the class returned if the query covered multiple classes, join, etc.  Don't try to use that since it that was not really widely implemented but we had to provide for it in the api.  Thus, to get the generator, you use:

```

        q_result = conn.IterQueryInstances(ql, query, namespace=ns,
                                           ReturnQueryResultClass=rqrc_param,
                                           OperationTimeout=ot,
                                           ContinueOnError=coe,
                                           MaxObjectCount=moc)

        result_insts = [inst for inst in q_result.generator]

We will fix the notebook for 0.14.2 release.

**Comment by KSchopmeyer** [comment]
There is a pr (pr #1472) for this change submitted.

**Comment by tanshaolong** [comment]
Thanks for your help.

Yes, the generator is a iterator. Currently, I can be iterable instances from the result. 
Also, the return from the IterQueryInstances has the third property(instances) besides query_result_class and generator. We can get the instances list by the instances property directly.

**Comment by tanshaolong** [comment]
I use 'CQL' as query language, but I get 'CIM_ERR_QUERY_LANGUAGE_NOT_SUPPORTED' error code. I think the issue as CIM agent(I use IBM SVC provider as CIM agent). Is it right? Thank you.

below is the detail error message.
```
query_language = 'DMTF:CQL'
inst_iterator = conn.IterQueryInstances(query_language, query,MaxObjectCount=max_obj_cnt)
2019-04-24 21:09:02,954-pywbem.api.4-11704-Request:4-11704 ExecQuery(Query='Select * from IBMTSSVC_StorageConfigurationService where name = "00000200A783AE32"', QueryLanguage='DMTF:CQL', namespace=None)
2019-04-24 21:09:03,124-pywbem.api.4-11704-Exception:4-11704 ExecQuery(str )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/pywbem/pywbem/cim_operations.py", line 6281, in IterQueryInstances
    namespace=namespace, **extra)
  File "/root/pywbem/pywbem/cim_operations.py", line 4175, in ExecQuery
    **extra)
  File "/root/pywbem/pywbem/cim_operations.py", line 1823, in _imethodcall
    code, desc, instances=err_insts, conn_id=self.conn_id)
pywbem.exceptions.CIMError: 14 (CIM_ERR_QUERY_LANGUAGE_NOT_SUPPORTED): CIM_ERR_QUERY_LANGUAGE_NOT_SUPPORTED: DMTF:CQL
```

**Comment by KSchopmeyer** [comment]
Reply to issue about CQL.   I assume that the terminology CIM_Agent is what we generally refer to as the WBEMServer (i.e. the entity you call with the WBEMConneciton url and which process WBEM requests like ExecQuery)

This response means that the WBEM Server or at least the component in the WBEM server (provider) you are querying does not support CQL query processing.  That is not a pywbem issue since the server is responding that it cannot handle the CQL based query. 

The implementation of CQL was always an option for each WBEM Server implementation, and even how they do it.  Thus, a server may not support the CQL query at all or possibly the particular class (there is a provider in the server for each CIM class that the server understands that generates instance responses) being queried may not support processing a CQL query and not have an alternative.  OpenPegasus, for example, supports CQL for requests in two ways.  

1. If the provider for that class has the code to process a CQL query, the query is passed to that provider (that is the fast path since the only instances generated for the response are the ones that pass the query. If the provider in OpenPegasus for the class defined in the query does not support CQL, OpenPegasus passes an EnumerateInstances to the provider and then filters the response (i.e. the response instances get generated and then discarded within the WBEM server, which is slower). 

2. Not all WBEM servers actually provide this second level of CQL processing (server filters if provider cannot process CQL) however; the provider in the server may generate the no CQL exception.  So it is difficult to say at exactly what level in the server it is returning the CIM_ERR_QUERY_LANGUAGE_NOT_SUPPORTED exception. 

But in any case that WBEM Server cannot process that a CQL based ExecQuery request.

**Suggestion: try WQL.**  Here are a couple of references to WQL.  If you keep the query simple, it will probably work or at least you will learn if your target supports WQL.

1.  The WQL specification used by OpenPegasus: https://wiki.opengroup.org/pegasus-wiki/lib
/exe/fetch.php?media=doc:dsp0104.htm

2. Some Microsoft documentation for WQL for wmi: https://docs.microsoft.com/en-us/windows/desktop/WmiSdk/wql-sql-for-wmi and https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_wql?view=powershell-5.1

Remember that while WQL is still being used in Windows WMI, etc. that is a quite a number of years different than what we built for OpenPegasus before DMTF decided to go the direction of CQL.

By the way, the Jupyter Notebook issue will be released next week or so with the 0.14.2 revision to pywbem.

SUGGESTION: When you come up with other questions, start a new issue for each since that makes it easier to keep track of the issues state of changes that result from the issue, etc.

**Comment by tanshaolong** [comment]
Got it. Thanks for your detail reponse.

**Comment by KSchopmeyer** [comment]
We are closing this issue as:

1. initial problem fixed.

2. Second problem apparently answered in that tan reponde thanks.
