### ISSUE TITLE
Associated optimization

### ISSUE THREAD

**Issue by allen0817** [pywbem/pywbem#1753]
pywbem 0.10.1
python 2.6.6

code 
source = conn.EnumerateInstanceNames('HITACHI_StorageVolume')
for s in source:
...     cs_inst = conn.GetInstance(s)
...     dmsg = conn.Associators(cs_inst.path,'HITACHI_SCSIPCForStorageVolume','HITACHI_SCSIProtocolController')

There are more than 90 sources, and each query is linked through the related class. It takes 10 seconds to loop once and about 15 minutes to loop 93 times. This is also too slow

**Comment by andy-maier** [comment]
Unless you need the cs_inst for some other reason, let me point out that you don't need it for the Associators operation. So you could save the GetInstance operations.

Also, I assume (not knowing the model by heart) that the HITACHI_SCSIProtocolController instance is always the same instance, so there is no point in discovering the same instance over and over again through the class that potentially has the most instances from all (HITACHI_StorageVolume).

When you say that 10 seconds for one loop turn is too slow, I cannot see what we can do in the pywbem client. We know there are some performance issues with large numbers of instances in the operation result set (that we have mostly addressed in pywbem 0.14), but these two operations you show in your code in the loop each return a single instance. You can turn on statistics (search for it in the pywbem docs) to show whether the time is spent in the pywbem client or in the server.

BTW, we are not changing anything anymore on pywbem 0.10. That version is out of service for a long time now. Also, Python 2.6 is out of service for a very long time now, and pywbem will drop support for Python 2.6 in the upcoming pywbem 1.0.

**Comment by KSchopmeyer** [comment]
From what we know without actually repeating the test:

1. In a number of environments the association operations are slow largely because of the algorithms used to determine what are the associations, filters, etc.  Unlike enumerate which just gets a list of instances with the defined class name and subclass names of the target class, the association operation must find instances of the class that have a reference that matches the instance it requested and then possibly filter for association class (and subclasses), result class (and subclasses) as well as filter out for roles based on the input parameters.

2. From the pywbem point of view, our time consumer is parsing the input xml and producing instances so the processing time is linearly related to a) the number of instances, b) the size of each instance. Using the latest release, we are processing 1000 - 2000 instances per second in a response.

3. Of course, there is additional time in processing requests (creating, sending) but this has proven to be a very small portion of the overall cim operation processing time in  what we have seen to date.

4. Here are some suggestions:
   a. I am not sure about the Hitachi environment, but a number of the providers have tools to allow the server to return its server time as part of the response.  That is the good news.  The bad news is that for each server, the activation mechanism might be proprietary.  Pywbem added code in about 0.12.0 to capture this time if it is transmitted from the server as part of the response and to set it into one of the variables of the WBEMConnection when the debug flag is set. Starting with about the same release we also capture our measurement of response time for each operation and save it in a WBEMConnection variable. Also, as andy stated, we have the statistics option that gives good information on the statistics of a group of operations.

 b. I agree with Andy that the versions of Python and of pywbem are very out of date. Would it be possible to update them. By the way, if possible, we are pushing to have clients move to Python 3 if possible since, while we will continue to support python 2, the Python org has deprecated it and will drop support "soon".  Also, as Andy said, you do not need the getInstance.  The EnumerateInstanceNames gives you everything you need to do the associations.

c. I can run a test and see what kind of results we get back.

However, I suspect that unless you are receiving thousands of instances back from the association requests, the real issue is probably in the serverand the time to resolve each association. However, the only way we can prove that is through a test.  There is at least one Hitachi server in the SNIA test bed that I can test against but I am not sure if it will give the same information.

**Comment by allen0817** [comment]
How can I associate other properties without cs_inst? Can I use the same GetInstance for different association classes



> Unless you need the cs_inst for some other reason, let me point out that you don't need it for the Associators operation. So you could save the GetInstance operations.
> 
> Also, I assume (not knowing the model by heart) that the HITACHI_SCSIProtocolController instance is always the same instance, so there is no point in discovering the same instance over and over again through the class that potentially has the most instances of all (HITACHI_StorageVolume).
> 
> When you say that 10 seconds for one loop turn is too slow, I cannot see what we can do in the pywbem client. We know there are some performance issues with large numbers of instances in the operation result set (that we have mostly addressed in pywbem 0.14), but these two operations you show in your code in the loop each return a single instance. You can turn on statistics (search for it in the pywbem docs) to show whether the time is spent in the pywbem client or in the server, if you want to follow up on this.
> 
> BTW, we are not changing anything anymore on pywbem 0.10. That version is out of service for a long time now. Also, Python 2.6 is out of service for a very long time now, and pywbem will drop support for Python 2.6 in the upcoming pywbem 1.0.

How can I associate other properties without cs_inst? Can I use the same GetInstance for different association classes

**Comment by allen0817** [comment]
> From what we know without actually repeating the test:
> 
> 1. In a number of environments the association operations are slow largely because of the algorithms used to determine what are the associations, filters, etc.  Unlike enumerate which just gets a list of instances with the defined class name and subclass names of the target class, the association operation must find instances of the class that have a reference that matches the instance it requested and then possibly filter for association class (and subclasses), result class (and subclasses) as well as filter out for roles based on the input parameters.
> 2. From the pywbem point of view, our time consumer is parsing the input xml and producing instances so the processing time is linearly related to a) the number of instances, b) the size of each instance. Using the latest release, we are processing 1000 - 2000 instances per second in a response.
> 3. Of course, there is additional time in processing requests (creating, sending) but this has proven to be a very small portion of the overall cim operation processing time in  what we have seen to date.
> 4. Here are some suggestions:
>    a. I am not sure about the Hitachi environment, but a number of the providers have tools to allow the server to return its server time as part of the response.  That is the good news.  The bad news is that for each server, the activation mechanism might be proprietary.  Pywbem added code in about 0.12.0 to capture this time if it is transmitted from the server as part of the response and to set it into one of the variables of the WBEMConnection when the debug flag is set. Starting with about the same release we also capture our measurement of response time for each operation and save it in a WBEMConnection variable. Also, as andy stated, we have the statistics option that gives good information on the statistics of a group of operations.
> 
> b. I agree with Andy that the versions of Python and of pywbem are very out of date. Would it be possible to update them. By the way, if possible, we are pushing to have clients move to Python 3 if possible since, while we will continue to support python 2, the Python org has deprecated it and will drop support "soon". Also, as Andy said, you do not need the getInstance. The EnumerateInstanceNames gives you everything you need to do the associations.
> 
> c. I can run a test and see what kind of results we get back.
> 
> However, I suspect that unless you are receiving thousands of instances back from the association requests, the real issue is probably in the serverand the time to resolve each association. However, the only way we can prove that is through a test. There is at least one Hitachi server in the SNIA test bed that I can test against but I am not sure if it will give the same information.

Thank you very much for your help. I have no external environment to test for you

**Comment by andy-maier** [comment]
Hi Allen.

On:
> How can I associate other properties without cs_inst? Can I use the same GetInstance for different association classes

I don't understand these questions. Let me try to explain some things, and then please ask again.

The Associators operation navigates from a source instance across association instances to associated instances. There are no properties in the game.

What is used from the source instance is only its instance path, not the entire instance. That's why I pointed out that the GetInstance operation is not necessary for just the Associators operation.

**Comment by andy-maier** [comment]
Let me also come back to the question why you need to navigate from the rather large number of instances of HITACHI_StorageVolume to the larger small (probably always the same) instance of HITACHI_SCSIProtocolController?

First enumerating the large number of HITACHI_StorageVolume instances, and then in a loop invoking Associators to cross the association to probably always the same HITACHI_SCSIProtocolController instance is pretty ineffective.

**Comment by andy-maier** [comment]
Closed due to inactivity. Feel free to reopen.
