### ISSUE TITLE
ConnectionError exception issue

### ISSUE THREAD

**Issue by tanshaolong** [pywbem/pywbem#1765]
Hi Everybody,

In term of IBM SVC CIM develope guide, I am using “CreateOrModifyStoragePool” method to remove backend volumes from a storage pool. I get a http bad status exception but I am sure my envirment don’t have any connection issue. Becouse I once remove the “InExtents” parameter from the “Params”, the exception will disappearce and the result is 0 (it mean the function is successful). I get the exception when the 'InExtents' just is included at Params.

The below code is detail for my issue:
```
Params = [('Pool', csp_paths[1])
         ('InExtents', bv_list),
         ('Force', True)]
result, outparams = conn.InvokeMethod('CreateOrModifyStoragePool', scs_paths[0], Params)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/pywbem/pywbem/cim_operations.py", line 4081, in InvokeMethod
    result = self._methodcall(MethodName, ObjectName, Params, **params)
  File "/root/pywbem/pywbem/cim_operations.py", line 2040, in _methodcall
    conn_id=self.conn_id)
  File "/root/pywbem/pywbem/cim_http.py", line 981, in wbem_request
    conn_id=conn_id)
pywbem.exceptions.ConnectionError: The server closed the connection without returning any response
```
I think my code should not run to the BadStatusLine exception. How can I avoid the issue? Please give some suggestions. Thanks you very much.

Best regards
Ray

**Comment by andy-maier** [comment]
I suspect that some of the input parameters are invalid or not supported by the SVC implementation. 

However, that should result in an Error response with an appropriate CIM status and a description that points out the issue. Closing the connection in such a case is very bad behavior, first because it does not provide any information about what was wrong, and second because it does not conform to DSP0200.

IMO you should open a PMR against the SVC implementation.

**Comment by tanshaolong** [comment]
Thanks for your response.
