### ISSUE TITLE
Many tests failing (tocimxml or tocimxmlstr or test_cim_xml or test_command or test_display_repository)

### ISSUE THREAD

**Issue by mcepl** [pywbem/pywbem#2004]
After #2003 I still get many tests failing on openSUSE/Tumbleweed (with Python 3.7), so much so that in order to make pytest passing I have to add ``-k 'not (tocimxml or tocimxmlstr or test_cim_xml or test_command or test_display_repository)'`` to my pytest call.

Any idea what’s going on? Is there something wrong with my configuration of the environment, missing dependencies, or something?

[Complete build log with all details](https://github.com/pywbem/pywbem/files/3933093/_log.txt)

**Comment by andy-maier** [comment]
Hi Matej,
the build log you are linking to does not contain much. Do you have one with more details?

**Comment by mcepl** [comment]
[_log.txt.zip](https://github.com/pywbem/pywbem/files/3933346/_log.txt.zip)

I am sorry about that. Is this better?

**Comment by andy-maier** [comment]
Hi Matej. I looked at the new log file and found the following failures:

* failure to run the wbemcli command: Not sure how you package the wbemcli command, but apparently it is not found. Note that we have deprecated the wbemcli command in favor of the pywbemcli command that comes in the pywbemtools package. So if you do not package the wbemcli command, you can exclude `test_wbemcli.py` (that's more reliable compared to excluding `test_command` as you did, in case we restructure the test functions inside of `test_wbemcli.py`). Let us know in case you do package the wbemcli command. Note that Fedora/Ubuntu packages the wbemcli command under the command name `pywbemcli` because they already have the wbemcli command from SBLIM under that name.

* failures in all tocimxml() and tocimxmlstr() tests, and in test_cim_xml: This is caused by the `xmllint` command not being there. It is a dependency for testing. See the OS-level dependencies for testing that are installed by `pywbem_os_setup.sh develop`.

* failure in test_display_repository: Caused by PLY issuing "Generating LALR tables" and the pywbem test not toleratng that. I can fix that by adding toleration for this.

**Comment by mcepl** [comment]
Right, so the first two are PEBKAC (I guess adding ``%{buildroot}%{_bindir}`` to ``$PATH`` should make the trick, right?), and the last one is something weird, which I cannot resolved easily.

Thank you very much for your help.

**Comment by andy-maier** [comment]
I am working to improve the situation with the last one. Reopening.

**Comment by andy-maier** [comment]
PR #2006 fixes that for master, and PR #2007 for 0.16.0.
The fix is described in the commit messages.
