### ISSUE TITLE
CIMQualifier flavors inconsistent with DSP0004

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#202]
The flavor-related parameters of CIMQualifier all have a default of None in the constructor.

DSP0004 and DSP0201 define defaults for the qualifier flavors. In terms of the ctor parameter names, these defaults are:
- overridable: True
- tosubclass: True
- toinstance: False (and deprecated).
- translatable: False

In DSP0201, flavors exist not only on qualifier types, but also on qualifier values. I believe the latter is because of the possibility to define qualifier types ad-hoc when used, and apparently we failed to deprecate that in DMTF. But that's a different story. Because defaults are defined, their presence in the CIM-XML is optional, and if not present, the above-mentioned defaults apply.

In pywbem, instance attributes for the flavors also exist in CIMQualifierDeclaration and in CIMQualifier, but their defaults are `None`.

**Discussion:** We should discuss whether we want to change the defaults for the flavor-related attributes to what DSP0004/DSP0201 define.

Considerations:
- Compatibility
- The DSP0201 defined defaults apply when the sender (client in a request or server in a response) does not specify the flavor attribute. The current defaults of `None` cause the flavors not to be specified and therefore invoke the application of the defined defaults on the receiving side. This is also some sort of default behavior.

**Comment by andy-maier** [comment]
This related to issue #203. Karl to address along with it.

**Comment by KSchopmeyer** [comment]
That compiler code is wierder than you would think.  Depending on the call and data, the function _build_flavors can receive as the flist input :

a) an empty string,  qual decl with no Flavor option
b) a list of flavor strings, qualifier
c) a dictionary of flavors and their values. 

Apparently it was never tested with a single flavor in a qual decl since that just generates an empty string for the flist.  If there are multiple entries in the Flavor definition of a qualifier declaration it builds a dictionary with all of the flavors defaulted in p_default_flavor) and overlays this with entries from the list so that build_flavors receives a dictionary. This is probably correct behaviour  If it is processing a qualifier, it builds a list and passes it to _build_flavors.

Guess there is more to fix than I thought.

**Comment by KSchopmeyer** [comment]
We need to resolve this discussion before I complete the rest of the flavor issues.  The alternatives are:

Qualifier Declarations and default definition of the flavors
1. Leave it as it is with None a logical input for these flavors
2. Add documentation that None really means nothing in the context of a qualifier and that the user should always supply all values.
3. Fix it so that the default for these parameters matches the defined default per DSP0004.
4. Leave None as the default but use the __init__ function to set these parameters consistent with DSP0004 if the input is None.

Since I would assume that the use of adhoc qualifiers types is minimal within the existing environments, I propose 3 above (force the defaults on the input parameters to the DSP defined default.

Question: Should the same apply to the definition of qualifier value???

**Comment by andy-maier** [comment]
After the discussion today in the call, here is my proposal, for review. It starts from the idea that we want to be able to support a true round-trip between MOF and CIM objects (even if we don't have that today):

- For both `CIMQualifierDeclaration` and `CIMQualifier`, the default values of flavors in the constructor stay `None`, and the corresponding member variables also are stay `None` if `None` was specified or defaulted. So these objects truthfully represent the flavors that were **specified** in MOF.
- For easy determination of the effective values of the flavors, add respective methods to `CIMQualifierDeclaration` and `CIMQualifier`. For `CIMQualifierDeclaration`, these methods take what was specified from the member variables of the object, and in case of `None`, fall back to hard coded DSP0004-defined defaults. For `CIMQualifier`, these methods take what was specified from the member variables of the object (these are now non-standard ad-hoc flavors a la M*soft), and fall back to the effective values of the corresponding qualifier declaration.

**Comment by andy-maier** [comment]
We agreed to move this to 0.10.0, because it depends on the option we decide for w.r.t. whether we remove defaults from generated output mof.

**Comment by andy-maier** [comment]
**Discussion point:** Where should we go with this?

**Comment by andy-maier** [comment]
Karl wants to do some more digging on this one, and we get back to it after 0.10.0.
