### ISSUE TITLE
MOF parser: Conflicting qualifier flavors go undetected

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#204]
If the qualifier declaration in MOF specifies conflicting flavors (e.g. both EnableOverride and DisableOverride), the last one encountered currently wins in the pywbem MOF compiler (see `_build_flavors()` in `mof_compiler.py`).

DSP0004 defines the following rules:
- Flavor (ToSubclass) and flavor (Restricted) shall not be specified both on the same qualifier type. If none
  of these two flavors is specified on a qualifier type, flavor (ToSubclass) shall be the implied default.
- If flavor (Restricted) is specified, override permission is meaningless. Thus, flavor (EnableOverride) and flavor (DisableOverride) should not be specified and are meaningless if specified.
- Flavor (EnableOverride) and flavor (DisableOverride) shall not be specified both on the same qualifier
  type. If none of these two flavors is specified on a qualifier type, flavor (EnableOverride) shall be the
  implied default.

**Proposed solution:**
1. Detect conflicting flavors (e.g. in `_build_flavors()` in `mof_compiler.py`) and raise MOFParseError in case of conflicts. Conflicting flavors are ToSubclass & Restricted, and EnableOverride & DisableOverride.
2. The rule not to specify EnableOverride or DisableOverride in case of Restricted, is only a recommendation. No exception should be raised, if violated. Instead, the notion of "meaningless" should be implemented somehow, e.g. by setting the `overridable` attribute to `None` if `tosubclass` ends up being `False`. This question is basically in the same category as the application of default values (see issue #203) and should be handled consistently with that.

**Comment by andy-maier** [comment]
**Discussion:** Discuss proposed solution.

**Comment by KSchopmeyer** [comment]
The problem presented by the code is more complex than the discussion above in that _build_flavors is used at two points in the compiler
1. Building Flavors when processing a CIMQualifierDeclaration
In this case the conclusions are correct in that we want to assure that conflicting flavors are rejected.
2. Processing a qualifier usually in a class where a CIMQualifier declaration already exists
In this case we not only want to assure that conflicting flavors are rejected but since there is already an existing qualifierDeclaration we need to determine if we want to really process the qualifier in terms of that declaration. Thus, if Override is not allowed in the decl do we want to allow in in the class definition or let this be passed on to the repository? Note that we process only for the existing class and do not take into account the superclass.

**Comment by KSchopmeyer** [comment]
Note that there is actually another limitation, Translatable may only be specified on qualifiers with datat type string or array of strings.  We should probably incorporate that also.

**Comment by KSchopmeyer** [comment]
Lets fix the small issue now and write a new issue for the larger issue.

**Comment by andy-maier** [comment]
One discussion point is how many exception classes will we have.

**Comment by KSchopmeyer** [comment]
Andy is worried about the CIMError being generated by the parser itself. 

We want something so that we put errors like invalid superclass in terms of the repository context and the class being compiled, not just a response from the repository itself.  Thus it should say something line superclass does not exist as opposed to what we would probably get from a repository 'CIMError, class does not exist' 

Should we have multiple classes for these errors or keep the mofparseerror exclusively for the yacc.
We need a name for the new class.  Lets call it MOFError and we could have a mofbase error that can be used by mofparseerror and MOFError.

**Comment by KSchopmeyer** [comment]
We agreed that we would allow 3 exceptions through this:
1. CIMError if passed from the repository connection call
2. MOFParseError from the yacc parser. Question. What does the lexer generate?
3. MOFSemanticError for everything else.

**Comment by KSchopmeyer** [comment]
In reflection I think we are just complicating things by doing another error.  There are other ways to separate the information to give a better picture of where the error came from and adding more exceptions simply complicates the user code.  We need to expand MOFParseError slightly for more information and consistency.  See issue #169 which also discusses issues with MOFParseError.

**Comment by andy-maier** [comment]
Agreed.

**Comment by andy-maier** [comment]
**Discussion point:** What is left from this issue?

**Comment by andy-maier** [comment]
The original issue stated was fixed in PR #423.
In the call today, we agreed:
- The discussion about the different exception classes can be closed. We go with `MOFParseError` for MOF parse errors, and `CIMError` for semantic errors.

**Comment by andy-maier** [comment]
In the call today, Karl and I agreed on the proposal.

**Comment by andy-maier** [comment]
Let's consider the exception question closed (no change needed), and go back to the original issue which was about the possibility to set conflicting qualifier flavors.

I don't think we need to go as far as checking everything related to flavors, but instead just what I proposed. Let's not make the issue larger, but let's discuss whether my originally proposed solution is a fair solution to solve some parts of the larger issue. I'm happy to reduce the proposal to just its item 1. That can be done locally in the `CIMQualifierDeclaration` class.

**Comment by andy-maier** [comment]
Proposed item 2 was addressed in PR #423 (pywbem v ....)
