### ISSUE TITLE
Create end2end testcases from run_operationtimeouts.py

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#2181]
Convert run_operationtimeouts.py into an end2end testcase

**Comment by KSchopmeyer** [comment]
There is a significant difference between the run_cimoperationtimeout tests and a end2end test for timeout in that the  current tests runs a whole sequence of tests looking for when the client will timeout and I assume that the end2end will probably want a simple delay that works and delay that fails test.    Second, this is a Pegasus only test in that it depends on the server having a provider that can delay responses so  it will  be limited to pegasus.

**Comment by andy-maier** [comment]
Are the extra tests in run_cimoperationtimeout that go beyond a simple deplay that works and one that fails, worthwhile?
If so, they should also go into the en2end test. If not, the run_cimoperationtimeout script should be dropped after creating the new end2end tests.

**Comment by KSchopmeyer** [comment]
Karl thinks this one is done.

**Comment by KSchopmeyer** [comment]
Action Karl - Find PR where this fixed

**Comment by KSchopmeyer** [comment]
Yes this issue was fixed with issue #3074.  Note that the original manual version of the timeout test is still in place and I think should remain in place since it is more of a broad test of timeout over a time range rather than just a confirmation of specific timouts.

**DISCUSSION:** I propose we close this PR as complete.
