### ISSUE TITLE
Rename the mocker _defaultinstanceprovider.py file

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#2231]
1. Move the dispatcher to its own file.

2. Change name of DefaultInstanceProvider to Name from powerpoint.  Karl put each of these in its own file.

**Comment by andy-maier** [comment]
Note: The `_defaultinstanceprovider.py` file contains these classes:
* class ProviderDispatcher(BaseProvider):
* class InstanceWriteProvider(BaseProvider):
* class MethodProvider(BaseProvider):
The file names are not stated in the design presentation, and that's why I could not find the name "DefaultInstanceProvider" in the presentation.

How about splitting out each of the three classes into its own file?

**Comment by andy-maier** [comment]
Mostly addressed in PR #2236
