### ISSUE TITLE
Include tests on pypi tarball

### ISSUE THREAD

**Issue by pacoesteban** [pywbem/pywbem#2260]
I'm updating the OpenBSD port for pywbem.  Our ports infrastructure usually get the distfiles for python ports from pypi.  It would be very useful to have the tests included on this distribution so we could execute them before packaging.

Thank you.

**Comment by andy-maier** [comment]
If we add the tests, it would be done by defining an "extra" in the setup.py file that installs the tests. The extra would not just contain the `tests` subtree, but additional files such as the makefile, dev-requirements.txt and several other files that are needed to run the tests.

The name of the extra could be whatever the convention is for tests (probably "tests"), and in case of pywbem you would need to invoke `make test` and check for rc=0.

Would that suit your needs?

**Comment by pacoesteban** [comment]
Hi Andreas,

I'm not sure what the "extra" on setup.py will do (not really my field), but our ports infrastructure forbids downloads at build time.

My understanding is that if you include the tests on the MANIFEST.in file (something like `"recursive-include tests *"`, but again not my field, you probably know better than me) they will get packaged on the tarball that gets distributed via pypi, that would be great in this case.

Are you open to that kind of approach ?

About the makefile, it could be a guide for us, but not really useful because it tries to do things like `$(PIP_INSTALL_CMD) $(pip_level_opts) -r dev-requirements.txt`and, as I said download at build time is not allowed.  But that's our problem, to provide the necessary dependencies before executing our test target.

Thank you.

**Comment by andy-maier** [comment]
I would like to avoid that every user pf pywbem is burdened with the test files. Simply adding the test files to the manifest file would do exactly that. That's why I proposed the "extras" approach. For example, an extra with name "tests" is installed via `pip install pywbem[tests]`. The extra would take care of its prerequisites, so `make test` would not download anything. We could even agree that we enable `setup.py test` to invoke just pytest.

**Comment by andy-maier** [comment]
Karl and I dicussed this and we want to give it a try (with an extra for installing the test files and dependent packages, and with "setup.py test" for running the test.)

**Comment by pacoesteban** [comment]
I understand your point about not wanting to distribute tests for those who don't need it.  I'm still not sure we'll be able to use it, I'll revisit this when 1.0.0 is out and let you know.

In any case, thank you.  Not all upstream maintainers are so easy to communicate with.

**Comment by andy-maier** [comment]
Meanwhile, I did some research on putting the tests into an "extra", but it was disappointing. It turns out that currently, extras only allow specifying additional package dependencies, but not additional files in the package itself. I have opened https://github.com/pypa/pip/issues/8451 to get a discussion on this started, but no reaction so far.

The main problem is how to have files in the Pypi package that are not always installed when a user installs the package, but just when requested, i.e. "optionally". I'm not so concerned about the size of the package on Pypi, but about the amount of files installed by a user of the package:

* pywbem and pywbem_mock modules: 43 files, 1.8MB
* tests subtree: 1762 files, 16.3MB (including the CIM schema that alternatively could be omitted in which case it is downloaded from DMTF during test but you said you cannot download during your test)

Did you run across any package on Pypi that includes the tests "optionally"?

One alternative for you might be to get the source tarball from GitHub, e.g. https://github.com/pywbem/pywbem/archive/0.17.3.tar.gz. The source tarball can be expanded and can be used for testing. We have an env var TEST_INSTALLED that  causes the installed version of pywbem to be tested, so you could use the source tarball just to get the tests and test against a version of pywbem that is installed by the OS-level package. We added this env var for Fedora packaging.

**Comment by andy-maier** [comment]
@pacoesteban I tried your original suggestion to add the files via the MANIFEST.in file, and that does in fact what I want, i.e. adding the files to the sdist archive but not to the wheel archive.

So I am now pursuing that approach. It also requires moving the "tests" subtree one level deeper, otherwise we install a global package named "test" ...

**Comment by andy-maier** [comment]
PR #2319 is a first stab at addressing this.

**Comment by andy-maier** [comment]
PR #2319 has been merged into master and will be released as part of our third beta 1.0.0b3, to be released within a week or so.
