### ISSUE TITLE
In change log of 1.0.0, separate pre-1.0.0 and just 1.0.0 changes

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#2303]
Because 1.0.0b1 is based on 0.14.0, the change log of 1.0.0b1 contains all changes since then. That makes it very hard for users to see which changes 1.0.0b1 provides on top of a version after 0.14.0, say the latest stable version 0.17.2.

We probably should show the change logs of the versions between 0.15.0 and 0.17.2, and reduce the change log for 1.0.0 to just the delta since 0.17.2.

DISCUSSION

**Comment by KSchopmeyer** [comment]
Sadly, I think we probably should break them out. Having seen the number of issues that pop up over what are minor things (i.e. the number of minor fixes to pywbemcli tests because of 1.0.0 incompatibilities) our user are probably going to need some help in transitioning.  

Originally I was thinking of the number of issues in pywbemcli iteslf that were the key, but it may well be the number things in the tests and that was larger.  pywbemcli went through to mutual compatibility with minimal change but we did a fair amount of test tweaking.

**Comment by andy-maier** [comment]
I agree

**Comment by andy-maier** [comment]
Fixed in PR #2307.
