### ISSUE TITLE
Make NocaseList (and NocaseDict) public?

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#2354]
**DISCUSSION**

**Comment by KSchopmeyer** [comment]
I see the upside.  What could the downsides be.

Upside:
1. Solid implementations that work for the special cases in CIM because of classnames, etc.
2. If we make them public, I think users will find uses within their apps since the case-insensitive components are fairly extensive in the pywbem CIM model.
3. I don't see any upside to keeping them private.

Downsides:

1.You might want to make separate library rather than part of pywbem.
2. Competes with some other python lib.  So far we have not found any for the list and the only one for the dict is what I used in pywbemcli tree (pydicti) and that was fairly special.  I.e. there is no reason for us to consider other libraries.

**Comment by andy-maier** [comment]
We agreed to turn both into Pypi packages.

**Comment by andy-maier** [comment]
The nocaselist repo has been created: https://github.com/pywbem/nocaselist
And version 1.0.0 released to Pypi: https://pypi.org/project/nocaselist/

**Comment by andy-maier** [comment]
I created issue #2356 for making NocaseDict public, targeting 1.1.0. This completes this issue for 1.0.0
