### ISSUE TITLE
Use twine for uploading to PyPI

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#242]
It seems that the missing information about dependencies on PyPI is caused by uploading via `setup.py upload`. The [twine](https://pypi.python.org/pypi/twine) package on PyPI does it correctly, plus it uses secure comunication with PyPI, which `setup.py upload` does not when running on Python 2.6.

We should start using `twine` for the upload. Yet another development dependency, but it seems to be worth it.

See issue #113 for details.

**Comment by andy-maier** [comment]
We agreed in the call today that we would go for it, even at the price of a new development dependency.

**Comment by KSchopmeyer** [comment]
A lot of my thinking was based on older projects where the goal was to severely limit the external toolset because of issues with developers having to install tools.  First, python makes much of that easy (m2crypt aside)  with Pypiand second, we have built that into our developer and install processes so in general I am no longer really concerned.  At the same time, it should be a project decision any time we add a new tool/ library probably mostly just to be sure we are using something that fully supports our goals, is supported, and is stable.

**Comment by andy-maier** [comment]
Addressed by PR #356.
