### ISSUE TITLE
mofcomp classes list is really a list of classnames in lower case.

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#243]
The class MOFWBEMConnection(BaseRepositoryConnection): has variables for classes and classnames that are populated after a compile:

self.class_names and self.classes.

However, the classes entry return a list of class names in lower case.  Mostly we need to clarify how this local repository should be used to retrieve classes post compile.  Note that EnumerateQualifiers does return the set of qualifiers.  This is for more than just our tests in that there are a number of uses for the in memory use of classes and qualifiers compiled from a schema so more than just the local tests will be using this in the future (ex. utilities, etc.)

Note that I have not yet dug into the code to determine details of which functions use class_names and which classes

**Comment by andy-maier** [comment]
MOFWBEMConnection is not a full local repository, I think. It is just good enough to record what happens to the underlying repository, in order to undo all of that when `rollback()` is called.

I think we need to get clear on what we expect from MOFWBEMConnection, and whether we want to develop it into something else.

**Comment by andy-maier** [comment]
Karl to analyze further.

**Comment by KSchopmeyer** [comment]
I think the only issue might be documentation

**Comment by KSchopmeyer** [comment]
Dumb mistake. Close as invalid
