### ISSUE TITLE
Bare except catches KeyboardInterrupt, prevents program termination.

### ISSUE THREAD

**Issue by skolsuper** [pywbem/pywbem#251]
This has been a long-standing minor annoyance in my daily life, when I run code using this library I can't stop it with SIGTERM or SIGINT, I have to use SIGKILL (in supervisor and PyCharm), so today I decided to track it down and it seems [this](https://github.com/pywbem/pywbem/blob/master/pywbem/cim_http.py#L643) is the offending line.

I don't know exactly what we're expecting to catch here but just specifying `Exception` allows `SystemExit` and `KeyboardInterrupt` to propagate. [source](https://docs.python.org/2/library/exceptions.html#exception-hierarchy)

**Comment by andy-maier** [comment]
Hi James,
Thanks for the analysis. I'll look into it.

**Comment by andy-maier** [comment]
The offending line is in a path for OpenWBEM. I trust you are not using that one??

**Comment by skolsuper** [comment]
Hi Andy,

I am not actually sure about that, so maybe?  Really my detective work only went as far as grepping for `except:` if I'm honest.  Maybe I jumped to conclusions too quickly, however changing the line in my local copy (I'm still working off the py3 fork my predecessor made) allowed me to stop the app in PyCharm.  My problem might also be related to asyncio, or a combination of the two.

`except Exception:` actually should still allow propagation of SystemExit and KeyboardInterrupt exceptions, so those lines, although a bit of a code smell, shouldn't be the cause of this issue.

Thanks for looking into it.

**Comment by andy-maier** [comment]
James,
I have created PR #261 that has debug prints to stdout for:

- any bare excepts (there is just the one you found)
- any excepts for Exception
- any retry loop continuations

I tried this version with `wbemcli` when it waited for a response from a non-reachable server, and it interrupted as desired on Ctrl-C, when run from the Linux shell directly. I did not try with PyCharm (not installed) or PyDev. None of the debug prints was encountered.

I suspect the problem is elsewhere, but not in the exception catching.

Could you please try out the code from this PR in your PyCharm environment and report back any debug prints it may display?

**Comment by andy-maier** [comment]
> I'm still working off the py3 fork my predecessor made

Note that starting with pywbem 0.8, we support Python 3. If you have any further changes due to Python 3, I'd be happy to integrate them.

**Comment by skolsuper** [comment]
Maybe the problem is with my code then (would not be the first time).  I still can't get `0.8` to work with Python 3 due to the issue reported in #150.  My predecessor's solution to the `check_hostname` problem was to drop Python 2 support, which I imagine is not palatable for the mainstream pywbem package.  In case you want to take a look at the changes, I think most of the relevant ones are in [this commit](https://github.com/cloud-hm/pywbem3/commit/ca5c726daba4258b76fab35243b3d7e01619a322)

**Comment by andy-maier** [comment]
James,
karl is making progress on the SSL fix.

On the SIGINT/SIGTERM problem: I am trying to reproduce that and I'm not able to. Here is what I do:

I use wbemcli from the latest master branch level on Python 2.7 on RHEL 6.7 from the command line, targeting an IP address on a virtual system that can be pinged but that does not have a WBEM server running.

In wbemcli, I invoke some function, say `ec()`. It waits for interaction with the server, which does not happen, so that gives me time to interact with this python session.

    (pywbem27)[maiera@oc1381478248 pywbem]$ PYTHONPATH=. ./wbemcli --no-ssl 192.168.122.238 -u maiera -p $mypassword -n root/PG_Interop

    Python 2.7.11 (default, Dec  7 2015, 11:26:11) 
    [GCC 4.4.7 20120313 (Red Hat 4.4.7-16)]
    
    Wbemcli interactive shell
    Connected to http://192.168.122.238 as maiera, default namespace root/PG_Interop
    Press Ctrl-D to exit
    Type h() for help
    >>> ec()

This invocation is always the same. Now I terminate it in different ways:

1. By pressing Ctrl-C:

        ^CTraceback (most recent call last):
          File "<console>", line 1, in <module>
          File "./wbemcli", line 542, in EnumerateClasses
            IncludeClassOrigin=ico)
          File "/home/maiera/Projects/pywbem/repos/pywbem/pywbem/cim_operations.py", line 2293, in EnumerateClassNames
            **extra)
          File "/home/maiera/Projects/pywbem/repos/pywbem/pywbem/cim_operations.py", line 670, in _imethodcall
            timeout=self.timeout)
          File "/home/maiera/Projects/pywbem/repos/pywbem/pywbem/cim_http.py", line 591, in wbem_request
            client.endheaders()
          File "/usr/lib64/python2.7/httplib.py", line 1053, in endheaders
            self._send_output(message_body)
          File "/usr/lib64/python2.7/httplib.py", line 897, in _send_output
            self.send(msg)
          File "/home/maiera/Projects/pywbem/repos/pywbem/pywbem/cim_http.py", line 341, in send
            self.connect()
          File "/usr/lib64/python2.7/httplib.py", line 836, in connect
            self.timeout, self.source_address)
          File "/usr/lib64/python2.7/socket.py", line 566, in create_connection
            sock.connect(sa)
          File "/usr/lib64/python2.7/socket.py", line 228, in meth
            return getattr(self._sock,name)(*args)
        KeyboardInterrupt
        >>> 

2. By sending SIGINT from a second terminal session to the PID of the python process running wbemcli:

   In second session:

        $ kill -s SIGINT $pid

   In the first session, it gets a 'KeyboardInterrupt` exception:

        Traceback (most recent call last):
          File "<console>", line 1, in <module>
          File "./wbemcli", line 542, in EnumerateClasses
            IncludeClassOrigin=ico)
          File "/home/maiera/Projects/pywbem/repos/pywbem/pywbem/cim_operations.py", line 2293, in EnumerateClassNames
            **extra)
          File "/home/maiera/Projects/pywbem/repos/pywbem/pywbem/cim_operations.py", line 670, in _imethodcall
            timeout=self.timeout)
          File "/home/maiera/Projects/pywbem/repos/pywbem/pywbem/cim_http.py", line 591, in wbem_request
            client.endheaders()
          File "/usr/lib64/python2.7/httplib.py", line 1053, in endheaders
            self._send_output(message_body)
          File "/usr/lib64/python2.7/httplib.py", line 897, in _send_output
            self.send(msg)
          File "/home/maiera/Projects/pywbem/repos/pywbem/pywbem/cim_http.py", line 341, in send
            self.connect()
          File "/usr/lib64/python2.7/httplib.py", line 836, in connect
            self.timeout, self.source_address)
          File "/usr/lib64/python2.7/socket.py", line 566, in create_connection
            sock.connect(sa)
          File "/usr/lib64/python2.7/socket.py", line 228, in meth
            return getattr(self._sock,name)(*args)
        KeyboardInterrupt
        >>> 

3. By sending SIGTERM from a second terminal session to the PID of the python process running wbemcli:

   In second session:

        $ kill -s SIGTERM $pid

   In the first session, it terminates the python process:

        >>> ec()
        Terminated
        $

I think this is how it should behave.

Could you please verify whether it works this way for you when you use your modified version with `wbemcli` on the command line (to exclude any influence from PyCharm or from the rest of your client side application)?

Is the waiting situation you try to interrupt, similar, or how does it look like?

**Comment by skolsuper** [comment]
Hi Andy,

Sorry for the slow reply, I am currently on holiday.  Thank you so much for looking into this so thoroughly.  It's looking very much like I was premature in assuming I had isolated the cause of my problem and raising this issue.  It's likely that my problem is with my code and how I am using asyncio, possibly also how I am using the rethinkdb asyncio driver.  When I am back in the office, I will verify by following the steps above and close this issue.

Thanks again,

James

**Comment by andy-maier** [comment]
Ok. We'll leave this issue open until you're back and have time to look into it.
No need to hurry.
Have a great holiday!

**Comment by skolsuper** [comment]
Have confirmed with current master branch that it's a problem on my end (PEBKAC).

Incidentally, I got a FileNotFound exception when using wbemcli the first time, as `~/.wbemcli_history` did not exist.  Possibly the error is caught in Python 2, but I think the exception catching there is not Python3 compatible yet and it threw again.

**Comment by andy-maier** [comment]
I also ran into the problem recently with Python 3 and forgot to open an issue. Thanks for mentioning it! I'll create one.
