### ISSUE TITLE
Don't response to call functions of WBEMConnection class from DCNM smi-s provider

### ISSUE THREAD

**Issue by tanshaolong** [pywbem/pywbem#2528]
Hello everybody:

I installed a Cisco DCNM 11.4.1 environment at windows as a smi-s provider. The DCNM had enabled smi-s feature. I can connect it by telnet with 5989 port. I don’t get response for waiting a long time when I call any functions of WBEMConnection  class. 
Below is my test code.
'''
import pywbem
server = 'https://192.168.2.33'
username = 'administrator'
password = '******'
namespace = 'root/cimv2'

conn = pywbem.WBEMConnection(server, (username, password),
                             default_namespace=namespace,
                             no_verification=True,
                             use_pull_operations=False)
conn.EnumerateClassNames(DeepInheritance=True)

'''
Would you please give me some help for my issues? 

Thank you
Ray

**Comment by andy-maier** [comment]
How does your code fail, i.e. which exception does it raise?

**Comment by tanshaolong** [comment]
> How does your code fail, i.e. which exception does it raise?

Don't get any output and any exception. Feel it suspension.

**Comment by tanshaolong** [comment]
I installed a new DCNM at LINUX with same version. I tried same code. I can get exception this time. Please see below:
‘’’
conn.EnumerateClassNames(DeepInheritance=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/pywbem/_cim_operations.py", line 8990, in EnumerateClassNames
    DeepInheritance=DeepInheritance)
  File "/usr/lib/python2.7/site-packages/pywbem/_cim_operations.py", line 1747, in _imethodcall
    self, request_data, cimxml_headers)
  File "/usr/lib/python2.7/site-packages/pywbem/_cim_http.py", line 323, in wbem_request
    raise ConnectionError(msg, conn_id=conn.conn_id)
pywbem._exceptions.ConnectionError: Failed to establish a new connection: [Errno -2] Name or service not known; OpenSSL version used: OpenSSL 1.0.2k-fips  26 Jan 2017
‘’’
I sure the dcnm have enabled smi-s because I can run telnet to 5989 port.
I sure the smi-s account is correct because I can login DCNM_SAN_Client with the account.
Why are they difference results for same code between linux with windows? Thank you.

**Comment by andy-maier** [comment]
Hi. I'm afraid we cannot help you there. It is almost certainly not pywbem's fault. The reason there are different error behaviors between Windows and Linux may be that the TCP stack is different, including possibly openssl has a different version. pywbem is just handing back the exceptions it gets from the requests package.

**Comment by KSchopmeyer** [comment]
1. The name or service not known is normally an issue where the server corresponding to a name cannot be found. I.e. DNS or your local doman resolution (ex. /etc/resolv.conf). cannot find correspondence for a name, at least in the pywbem connection setup. Since you are using an ip address that is strange; but even using the IP address is not completely straight forward

2. Test with ping to be sure that pinging that server works.

3. Openssl has some test client support that can help determine if it is getting to the host system SSL.   Try those commands with the same hostname/port and make a connect to see what ssl things of that host and port. 

4. What version of python and what version of pywbem are you using although I cannot believe that this can be causing the issue.

5. The other possibility could be SSL although I really do not thing this is the problem because if it was an SSL error it would be further into SSL and would get some form of SSL oriented error message.

I had this problem in years past with an OpenPegasus local environment in my testing of OpenPegasus (a CIMServer where I had the client and server on either the same machine or side by side test machines).  When at home in Dallas it worked but when I moved the same computers to a different internet provider in Indiana, in initially provided the same response error.   In that case, I am assuming that there was something different in between the router I was using at home and the one I used in Indiana.   Sadly I cannot remember exactly what I did it resolve the issue but it was network based, not the WBEM Client or server.  When the client connect was executed, that was the exception returned with the same message.

In any case, this is probably NOT a pywbem problem but a network issue of some sort involving the address resolution or caching of network information.

**Comment by KSchopmeyer** [comment]
Try some of the above suggestions and tell us what happened.

Good Luck

Karl

**Comment by tanshaolong** [comment]
Thanks @KSchopmeyer @andy-maier for your detail response.
You are right. It is not pywbem issue. It is not response yet when I used “openssl s_client” to test ssl connection. I will check Cisco DCNM document for resolving the issue.

:) Thanks you again.

**Comment by KSchopmeyer** [comment]
Feel free to ask more questions if you feel we can help.
