### ISSUE TITLE
CIM integer types have no notion of min/max values

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#268]
It is sometimes important to be able to retrieve the boundaries of the allowable value range for CIM integer types.

**Comment by KSchopmeyer** [comment]
Not sure under what circumstances but I can see a withinrange function (number, max, min) somewhere in the code as a usable function.  The next question is whether we should tie it to the qualifiers min and max in the mof_compiler however so that either defaults or instance compile should be checked for min/max value if they exist.

**Comment by andy-maier** [comment]
Agreed to have that in some form (e.g. class attribute on the Uint8 etc. classes).

**Comment by KSchopmeyer** [comment]
We will not do this for the mof_compiler
