### ISSUE TITLE
make check failure, notebook

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#2703]
Notebook 6.1.5 fixes open redirect vulnerability 'GHSA-c7vm-f5p4-8fqh'. See: |
| CVE-2020-26215.

**Comment by andy-maier** [comment]
It seems that the notebook package only recently added its vulnerabilities to safety checking. That can be seen by the satefy IDs which are all very recent: 40380 ... 40385. That's why older versions of notebook are suddenly stated to be a fix to the respective issue. Since we are running safety with out minimum-constraints.txt file, the minimum version 4.3.1 of the notebook package is used for the check. So far for explaining why they come up now.

**Comment by andy-maier** [comment]
On fixing the issue: notebook 6.1.5 which is the minimum version that fixes all of the issues runs on Python 3. only. So either we give up installing notebook on Python 2, or we ignore all thee new safety issues.
**DISCUSSION**

**Comment by KSchopmeyer** [comment]
Lets make our decision on python 2.7 all toghether, not component by component.  I agree with bypassing the safety failures for notebook, especially since it is not a component of the pypi code (at least I think  it is not).
