### ISSUE TITLE
Supported authentication mechanisms are not described

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#277]
The PyWBEM Client does not document which authentication mechsnisms it supports.

**Comment by andy-maier** [comment]
Resources:

* Good overview on the various mechanisms: http://blog.distributedmatter.net/post/2008/06/09/HTTP-authentication-mechanisms-and-how-they-could-work-in-Restlet
* DSP0200 1.4, section "Security Considerations"

**Comment by andy-maier** [comment]
Here is a stab at describing the possible authentication mechanisms in CIM-XML. This is what the CIM-XML protocol can do, in combination with what the underlying HTTP/HTTPS protocol can do, independent of whether all of that is supported by PyWBEM or by specific WBEM servers.

The following table combines the authentication method with the protocol, and states the requirement level for supporting each combination as specified in DSP0200. The Credentials column refers to the credentials that are provided as input to the whole authentication process; they are not always flowing over the network. The HTTP and HTTPS columns also show a short name for each possible combination (e.g. `BS`).

    ===================  ===============  ===================  ================
    Auth.Method          Credentials      HTTP                 HTTPS
    ===================  ===============  ===================  ================
    No Auth.             None             N: Not recommended   NS: Not recommended
    Basic Auth.          Userid/Password  B: Not recommended   BS: Optional
    Digest Auth.         Userid/Password  D: Recommended       DS: Recommended
    X.509 Client Cert.   None             N/A                  XS: Optional
    ... others ...       ???              ???                  ???
    ===================  ===============  ===================  ================

When HTTPS is used, a number of additional things apply to all of these authentication methods:

* During the SSL/TLS handshake, the client presents the possible SSL/TLS protocol versions and the possible cipher suites to the server. The server chooses one protocol version and one cipher suite and returns that information to the client. I'm mentioning this because one could think of client-side configuration settings that restrict the offered protocol versions and/or cipher suites.
* Also during the SSL/TLS handshake, the server may present an X.509 server certificate to the client, which the client must validate (according to RFC2617).

PyWBEM today supports the combinations: N, NS, B, BS, XS.

**Discussion points** (for support in the PyWBEM client):

1. Is the above description correct?
2. Should we add support for Digest Auth. (combinations D and DS)?
3. Are there other authentication mechanisms to add?
4. Should we add a way to restrict the offered protocol versions and/or cipher suites?
5. How should server certificate validation be done (i.e. where does the public key come from, do we verify the chain of trust, what out of that should be configurable)?
6. Where should the client certificate come from?

I'd like these answers to be discussed first in terms of the `WBEMConnection` API. Once we have a direction there, we can talk about command line options, config files, environment variables, etc. (see issue #216 for that).

**Comment by KSchopmeyer** [comment]
1. Not done
2. We have basic auth with httplib2.  However, apparently httlib2 does not include digest auth. Note that the requests package includes both basic and digest
>>> from requests.auth import HTTPBasicAuth
>>> requests.get('https://api.github.com/user', auth=HTTPBasicAuth('user', 'pass'))
<Response [200]>

>>> from requests.auth import HTTPDigestAuth
>>> url = 'http://httpbin.org/digest-auth/auth/user/pass'
>>> requests.get(url, auth=HTTPDigestAuth('user', 'pass'))

Of course, the key question here is exactly would the client determine what to use since it is the client that starts the communication?

Note that neither of these is really of great interest in the smi/snia world but may be in general pywbem usage.

3. Not unless we get into kerberos and we are not ready for that.

4. We don't have to worry about that. We simply need to a) be able to provide the correct keys and certs, and sort out which of the many ssl/http packages does the best job across all of our possible environments of handling the issue.  

Note that if we are going to validate a server sent cert we need to have a cert in the same ca tree.  The package will do the work of validating (that is the ca_cert option).  In addition to the client validating the received cert against the ca_certs (actually done by the ssl implementation, not by us, there is at least one other validation required, the match_hostname validation. That matches the host name info in the server cert against the host we requested.  That one is in varying states of implementation in the different implementations.

5. The client cert should come from a ca root that the server understands so that the server can confirm that it has a common ca root with the cert sent by the client.  Normally the client would maintain this as an individual cert  and corresponding private key.  

Here is the explanation of the client private key

the client has to sign the handshake messages in the Certificate Verify message of the TLS handshake so that the server can verify it against the public key sent in the client certificate. Without this step, no client-certificate authentication would be taking place.

This is an overview but we now need to take the chart and make it into a set of specifics for each version of pywbem as it is released.

**Comment by andy-maier** [comment]
Some more comments / findings on certificates and keys (e.g item 5, above):
* The certificate sent by the server during TLS/SSL handshake is sent in clear text (see http://www.zytrax.com/tech/survival/ssl.html). Therefore, the server certificate must not contain a private key, but instead only the public key.
* The http://www.zytrax.com/tech/survival/ssl.html page does unfortunately not cover mutual authentication, and the http://www.codeproject.com/Articles/326574/An-Introduction-to-Mutual-SSL-Authentication page does not go into the detail of showing which messages are sent unencrypted, but I have the suspicion that the client certificate must also not contain a private key.
* I think you found the only reason for specifying the client private key. Its use in the TLS/SSL handshake does not provide for a logon without username/password, because user level authentication happens at the HTTP level, not at the TLS/SSL level. So we need to take a closer look at HTTP for that.

**Comment by KSchopmeyer** [comment]
We want to add documentation about additional characteristics of https, in particular issues like match_hostname

**Comment by andy-maier** [comment]
This issue is addressed in PR #338.
