### ISSUE TITLE
Error in exception when calling with SSL and exception occurs

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#288]
Python 2.7

The exception after first send data
With python 2.7 (m2crypto) and no_verification=False: 

When you do an https connect with a script you the the exception below:

              except Exception as exc: # socket.error as exc:
                    # TODO AM: Verify these errno numbers on Windows vs. Linux.
                    print('exception exc %s' % repr(exc))

fails:

    Traceback (most recent call last):
      File "./dotestpeg.py", line 11, in <module>
        CLS = CONN.GetClass('CIM_ManagedElement')
      File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_operations.py", line 2513, in GetClass
        **extra)
      File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_operations.py", line 670, in _imethodcall
        timeout=self.timeout)
      File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_http.py", line 611, in wbem_request
        if exc.args[0] != 104 and exc.args[0] != 32:
    IndexError: tuple index out of range

**Edit:** Andy edited for better formatting.

**Comment by andy-maier** [comment]
The exception handler on line 610 of cim_http.py was catching `socket.error` at some point. That was quick-fixed to catching `Exception` when the support for Python 3 was added in commit 1836e67. I don't recall why that was done.

My suggestion for a fix is to catch `SocketErrors` instead. Also, before checking `exc.args[0]`, we should test that `exc.args` is a tuple or a list, and pass if not.

**Comment by KSchopmeyer** [comment]
32 is broken pipe and 104 connection reset.  We do not understand why these are here. We need to figure out when these were inserted.  The change to exception came with python 3 support.  We propose to simply remove this and let things fail or to raise a warning to ask theuser to report to the issue tracker.

**Comment by andy-maier** [comment]
I was digging in the history of this:

* The comment above the exception handling in cim_http.py describes the reason for it:

                # See RFC 2616 section 8.2.2
                # An http server is allowed to send back an error (presumably
                # a 401), and close the connection without reading the entire
                # request.  A server may do this to protect itself from a DoS
                # attack.
                #
                # If the server closes the connection during our h.send(), we
                # will either get a socket exception 104 (TCP RESET), or a
                # socket exception 32 (broken pipe).  In either case, thanks
                # to our fixed HTTPConnection classes, we'll still be able to
                # retrieve the response so that we can read and respond to the
                # authentication challenge.

* In pywbem 0.7.0, the code that lets errors 32 (EPIPE) and 104 pass, was already in. But only the `send()` call was protected by the exception. Sometimes later, I moved the `endheaders()` call also into the try clause, because `endheaders()` also sends data and could encounter these errors.

**DISCUSSION:** It is to be investigated whether that was a good or bad change.

* The *fixed HTTPConnection classes* mentioned in the comment probably refers to the fact that the `send()` method in pywbem's 'HTTPBaseConnection` does *not* have the code in that closes the connection upon error 32.

* In the standard Python code, the code in that closes the connection upon error 32 was removed from the `send()` method in the standard Python `HTTPConnection` class with the fix for [Python issue #5542](http://bugs.python.org/issue5542). This fix was integrated into Python 2.7 with [commit 8072dfd97e1d](https://hg.python.org/cpython/rev/8072dfd97e1d/) and into Python 3.1 or 3.2 (not sure) with [commit a726f7928561](https://hg.python.org/cpython/rev/a726f7928561/).

This means the fix in the pywbem `send()` method also made it into standard Python. However, the code that was copied meanwhile changed a bit in standard Python, in support of data arrays. Also, the fix in the standard Python code is not in Python 2.6. 

**DISCUSSION:** We should probably leave that fix in our `send()`, but update to the latest code handling data arrays.

As far as the exception handling in `wbem_request()` goes, ignoring error 32 is probably correct. It is not clear to me why error 104 needs to be ignored as well.

**DISCUSSION:** I think we should remove error 104 from being ignored.

**Comment by andy-maier** [comment]
PR #290 addresses these issues. Updated the previous comment to show how.

**Comment by andy-maier** [comment]
Once accepted, the change from PR #290 should be merged into the master branch.

**Comment by KSchopmeyer** [comment]
On 05/09/2016 02:59 AM, Andreas Maier wrote:
>
> I was digging in the history of this:
>
>  *
>
>     The comment above the exception handling in cim_http.py describes
>     the reason for it:
>
>     |# See RFC 2616 section 8.2.2 # An http server is allowed to send
>     back an error (presumably # a 401), and close the connection
>     without reading the entire # request. A server may do this to
>     protect itself from a DoS # attack. # # If the server closes the
>     connection during our h.send(), we # will either get a socket
>     exception 104 (TCP RESET), or a # socket exception 32 (broken
>     pipe). In either case, thanks # to our fixed HTTPConnection
>     classes, we'll still be able to # retrieve the response so that we
>     can read and respond to the # authentication challenge. |
>  *
>
>     In pywbem 0.7.0, the code that lets errors 32 (EPIPE) and 104
>     pass, was already in. But only the |send()| call was protected by
>     the exception. Sometimes later, I moved the |endheaders()| call
>     also into the try clause, because |endheaders()| also sends data
>     and could encounter these errors.
>
> *DISCUSSION:* It is to be investigated whether that was a good or bad 
> change.
>
>  *
>
>     The /fixed HTTPConnection classes/ mentioned in the comment
>     probably refers to the fact that the |send()| method in pywbem's
>     'HTTPBaseConnection` does /not/ have the code in that closes the
>     connection upon error 32.
>
>  *
>
>     In the standard Python code, the code in that closes the
>     connection upon error 32 was removed from the |send()| method in
>     the standard Python |HTTPConnection| class with the fix for Python
>     issue #5542 <http://bugs.python.org/issue5542>. This fix was
>     integrated into Python 2.7 with commit 8072dfd97e1d
>     <https://hg.python.org/cpython/rev/8072dfd97e1d/> and into Python
>     3.1 or 3.2 (not sure) with commit a726f7928561
>     <https://hg.python.org/cpython/rev/a726f7928561/>.
>
> This means the fix in the pywbem |send()| method also made it into 
> standard Python. However, the code that was copied meanwhile changed a 
> bit in standard Python, in support of data arrays. Also, the fix in 
> the standard Python code is not in Python 2.6.
>
We appear to be getting more and more little things where python 2.6 is 
out of the loop.  In you mind how much longer should we be fully 
supporting python 2.6?
>
> *DISCUSSION:* We should probably leave that fix in our |send()|, but 
> update to the latest code handling data arrays.
>
> As far as the exception handling in |wbem_request()| goes, ignoring 
> error 32 is probably correct. It is not clear to me why error 104 
> needs to be ignored as well.
>
> *DISCUSSION:* I think we should remove error 104 from being ignored.
>

Will test pr today with the code that hits the problem

Karl
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/pywbem/pywbem/issues/288#issuecomment-217799687>
>


-- 
================
Karl Schopmeyer
email: k.schopmeyer@swbell.net, k.schopmeyer@opengroup.org
tel: 972-814-5581

**Comment by andy-maier** [comment]
RHEL 6.x has Python 2.6 as its main Python and is still getting new update releases. I think there are some more distros that are that way. Python 2.6 started issuing a deprecation warning at some point, so i think there will now be increased focus by such distros on upgrading to 2.7. Hard to tell when they will be done. Several years, i guess.

**Comment by andy-maier** [comment]
PR #290 has been merged in order to ease the work on issue #179, but the resolutions should still be discussed (see discussion points further up).

**Comment by andy-maier** [comment]
PR #179 (merged) addresses that for 0.9, and PR #298 (not yet merged) addresses that for 0.8.
Once PR #298 has been verified and merged, this issue can be closed.

**Comment by andy-maier** [comment]
PR #298 has been merged. Closing this issue.
