### ISSUE TITLE
module mof_compiler depends on PG_InterOp ns name

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#29]
It appears that this particular namespace name is hardcoded into the compiler.

See the function _create_ns on about line 216

**Comment by andy-maier** [comment]
If I read this correctly, then this is code that attempts to support the `__Namespace` class in the `PG_InterOp` namespace for OpenPegasus, in case it does not support the `CIM_Namespace` class in the `Interop` namespace. The latter is also not quite complete. [DSP1033 1.1.0](http://www.dmtf.org/sites/default/files/standards/documents/DSP1033_1.1.0.pdf) defines for the name of the Interop namespace:
* Standard names are:
  - `interop` (preferred)
  - `/interop` (DEPRECATED)
  - `root/interop` (DEPRECATED)
  - `/root/interop` (DEPRECATED)
* Clients need to be prepared to deal with any one of these standard names.
* A WBEM server may expose Interop namespaces using additional implementation-defined names. This accommodates backwards compatibility of existing WBEM server implementations. Clients should use the standard names instead of such implementation-defined names.

By the way, I verified that the `mof_compiler` module has the only code in the PyWBEM client project that deals with the Interop namespace.

I think extending that code so that it supports all four standard names is something we should do in any case.

That code only special-cases for OpenPegasus. In any case, we can move that special case after the attempt to use the standard names.

The interesting question is can we remove that special code entirely. In which OpenPegasus version was the support for the standard class name and the standard Interop namespace names introduced?

**Comment by andy-maier** [comment]
We agreed to use the standard interop namespace names first. There are still current OP versions that can be configured with only the PG_Interop name, so that cannot be dropped and should be tried after the standard names.

**Comment by KSchopmeyer** [comment]
Consider removing the _Namespace support since it is deprecated.

**Comment by KSchopmeyer** [comment]
Karl will review this to determine if still valid.

**Comment by KSchopmeyer** [comment]
Yes this is still valid.  

1. A agree that starting with CIM_Namsepace is more logical and __namespace__ is only a final fallback position.

2. Why can't we use the code in wbemserver that finds namespaces and the interop namespace in place of this years old hack?  DISCUSSION

**Comment by KSchopmeyer** [comment]
In reviewing the code we found that if there is a namespace PG_Interop, mofcompiler assumes that it is pegasus and wants to use the __namespace class to create the namespace.  However, It appears that when mofcompiler tries to create a namespace using either __namespace or CIM_Namespace it tries to do it in the namespace being created, not the interop namespace.  We need to 👍

1. Review the rules in DSP 0200 for namespace creation in the spec to determine rules for the namespace in which the create requests are made (we assume it must be in the interop namespace).

2. Attempt to use the wbemserver class and add a create namespace operation to that class. Then the mofcompiler could delegate to this single place to do namespace creation and not leave it as hidden code in the compiler.

3. Even with pegasus, check to see if CIM_namespace exists and use it in place of __namespace.  The only time __namespace should be used is if CIM_Namespace does not exist.

**Comment by KSchopmeyer** [comment]
Note that DSP 0200 defines behavior for creating namespaces but specifies root as the namespace. This is incomplete, etc.  ACTION: Create mantis for change to this document

**Comment by KSchopmeyer** [comment]
This brings up the questions:

1. exactly what is the algorithm for the pseudo class __namespace to create and get namespaces.

2. Can you create two top level namespaces with the __namespace algorithm.  We think the answer is NO. If so should this be a clarification in the spec.

**Comment by KSchopmeyer** [comment]
What are the rules for creating the very first namespace in a server, i.e. CIM_Namespace does not exist at this point.

Andy brings up the issue of servers that have not yet installed the support for namespace creation. What do we do with them? We would get an error for testing with CIM_Namespace but (while not documented) was to be a "fixed entity" in a server and not dependent on installed providers.

**Comment by andy-maier** [comment]
I created issue #1311 to capture the creation of the Mantis issue.

**Comment by andy-maier** [comment]
I will approach this in two steps:

1. Add a method to the WBEMServer class for creating a namespace. This method will try several approaches on how a namespace can be created, in this order:

   * The new approach described in the WBEM Server profile DSP1092, i.e. via a method `CIM_WBEMServer.CreateWBEMServerNamespace()`. Given that this profile is unlikely to have wide adoption, I'd like to skip this for now but leave a TODO in the code.
   * CreateInstance on class `CIM_Namespace` against the Interop namespace as determined by `WBEMServer.interop_ns`.
   * Hierarchical series of CreateInstance on class `__Namespace` for each namespace segment starting at the top (i.e. at "/", not below "/root").

2. Use the new method in the MOF compiler.

**Comment by andy-maier** [comment]
PR #1318 addresses item 1 from the list above.

**Comment by andy-maier** [comment]
**Discussion point:** Invoking a WBEMServer method in the mof compiler functions is not as easy as I thought. One main issue is that creating a WBEMServer object requires a WBEMConnection object, and not just a BaseRepositoryConnection. This makes sense, because BaseRepositoryConnection defines only the operations that are used by the MOF compiler against the repository. WBEMServer however can potentially use any operation.

I see the following options:
* Do nothing - continue using `mof_compiler._create_ns()` within the MOF compiler.
* Eliminate the different set of operations between a repository connection and a full connection, by adding the missing operations to repository connections. That allows using the repository connection for the `WBEMServer` class, but also increases the burden of implementing a user-defined repository. It is however a good cleanup, because the subset has always only been motivated by what the MOF compiler happened to use, and also limited what the MOF compiler could do in the future.
* Move the new `create_namespace()` function to a different place than the `WBEMServer` class, so that it can be used by the MOF compiler. This is not a good option, because it would essentially require to remove the DSP1092 based namespace creation from the method (whose imlementation depends a lot on functionality in the `WBEMServer` class).

**Comment by andy-maier** [comment]
A third **discussion point**:

The implementation of the current `mof_compiler._create_ns()` when it uses the `CIM_Namespace` class, provides only the "Name" property in the new instance. In the CIM Schema, this class has six key properties.

DSP0200 states "A value is specified for the new instance parameter that defines a valid instance of the CIM_Namespace class and that has a name property that is the desired name of the new namespace."

The question is which of the six key properties, besides of course "Name", need to be provided?

**Comment by KSchopmeyer** [comment]
Action: Discussion 2: Karl determine when pegasus implemented the CIM_Namespace class.  I believe it was in the 2006 range but will confirm version and date.

Discussion point 3. If the other properties are key properties, We believe that only name is required. The other values should be supplied by the server on the response. Karl would like to confirm that against OpenPegasus.

**Comment by andy-maier** [comment]
PR #1339 addresses item 2 from the list further up.
