### ISSUE TITLE
Require minimum SSL/TLS version to TLS 1.0

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#295]
I propose to remove support for SSL 2.0 and SSL 3.0 from pywbem 0.9.

**Comment by KSchopmeyer** [comment]
The fix is simple; the goal is logical since SSL 2/3 have proven error prone and organizations like SNIA are dictating that they not be used. Also, typically it is the server that could control this minimum, not the client.

First, remember that generally the server sets a clear minumum. Servers like pegasus do enforce this minimum but even they offer an admin bypass.

However, we do not really know the requirements of all pywbem users so we can end up blocking users from any ssl connection if we do not offer some type of way to bypass this limit.   We also proposed on issue #286 that we provide some more control for the client to set minimums.   To me the logical is to set the default for both m2crypto for at least TSL 1.0 and then allow an optional parameter so that the user could force some other minimum.  This would mean extending our client script software to offer this additional optional minimum also.

We have 3 choices here:
1.  leave as is.
2.

**Comment by KSchopmeyer** [comment]
We propose that we set default for tls 1.0 and upwards and a variable to allow ssl 3.0 and another for ssl 2.0. These would not be part of the WBEMConnection because it is too complex already. this will be separate wbemconnection properties that can be set after the wbemconnection constructor and before the first operation.

**Comment by KSchopmeyer** [comment]
We feel for that 0.9.0 we will need to set the minimum as 1.0.  This is for both m2crypto and ssl module

**Comment by KSchopmeyer** [comment]
See also issue #65.  I think this should have been a 0.9.0 issue

**Discussion:** Should we make this one 0.9.0????

NOTE:  the Python 3 ssl module has a create_default_context function that does the following:

PROTOCOL_SSLv23 | OP_NO_SSLv2 |  OP_NO_SSLv3

to which the following are added
OP_NO_COMPRESSION
OP_CIPHER_SERVER_PREFERENCE - Prefer the servers ciphers
OP_SINGLE_DH_USE   - use single keys to improve forward secrecy
OP_SINGLE_ECDH_USE

Not sure we could match this with the python 2.7 m2Crypto setting mechanism, in particular since the documentation seems to almost not exist.

In reality this is as complete or more complete than we could offer for Python3.

Therefore I suggest that we seriously consider a modification to use the create_default_context in place of setting it ourselves.

Finally the have a list of restricted ciphers from the snia spec that they disallow.  We need to figure out how what the client should do about this

Note that very little of this exists for m2crypto.  I have not even figured out how to limit to tls 1.2 since rather than flags to set the context m2crypto use a string

**Comment by andy-maier** [comment]
As far as I can tell, the settings for the default context are exactly what we want!

So I agree that we should use the default context for SSL 3.0.

I'll post a question for M2Crypto w.r.t. setting these same settings there.

**Comment by KSchopmeyer** [comment]
We agreed:
1. move to 0.9.0
2. use the ssl default but copyt the code
3. Separate it so it is easy for someone to fix.

**Comment by KSchopmeyer** [comment]
We have an answer on m2cyrpto so will make that one tls only also

**Comment by andy-maier** [comment]
This issue was fixed in PR #373.
