### ISSUE TITLE
DSP0004 issue: Escaping issue with \ in tomof.  

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#312]
Issue in mofstr with enclosed single quote. tommof output drops the escaped single quote mark that is in at least description strings in mof.  It completely drops the single quote. See example below.

This is an issue with the mofstr function in that it does nothing special at all with single quotes in strings.   I need to double check but I believe that DSP0004 states that they are escaped.

The original mof was:

```
Description (
"Indicates the PowerSupply\'s input frequency range "
"measured by the associated sensor. Range 1, 2 or both "
"can be specified using the values 2, 3 or 4, "
"respectively." ),
```

The mofoutput is"

```
Description (
"Indicates the PowerSupplys input frequency range measured by the "
"associated sensor. Range 1, 2 or both can be specified using the "
"values 2, 3 or 4, respectively."),
```

But even stranger, the compiler produces the following error:

```
[Deprecated { "No value"},
Description (
"Indicates the PowerSupplys input frequency range measured by the "
"associated sensor. Range 1, 2 or both can be specified us
```

Edit: Andy edited for proper formatting of MOF.

**Comment by andy-maier** [comment]
Karl,
DSP0004 2.8 requires escaping only for double quotes. I would say that is incomplete, because you better also require escaping for backslashes; otherwise it is not clear whether two consecutive backslashes are an escaped single backslash or two unescaped backslashes.

**TODO(Karl):** Can you please open a Mantis issue on DSP0004 to add the requirement to escape backslashes as well?

The `mofstr()` function states that it plays it safe and escapes all short sequences. However, in both 0.8 and 0.9, it fails to do that for the single quote. That flaw must have been in there for quite some time.

I'll grab this issue and fix it for 0.8 and 0.9.

BTW, with such optional choices for escaping, you can always create MOF that fails the roundtrip: MOF -> parsed -> MOF. For example, given that `mofstr()` escapes the characters with optional escaping, you can supply them unescaped as MOF input, and they will result escaped in the MOF output, after the roundtrip.

We'll see that way whether the CIM Schema escapes these characters with optional escaping in all cases ;-)

**Comment by andy-maier** [comment]
We agreed on the call today that we would not roll this back to 0.8.

**Comment by andy-maier** [comment]
Reopened for Karl to follow on w.r.t. the DSP0004 todo.

**Comment by KSchopmeyer** [comment]
Karl action from above open mantis issue

**Comment by KSchopmeyer** [comment]
Andy.  I see the definition of escape for backslash in line 4224 (Section 7.12.1) of that spec and line 4487.  However in section 7.12.2 '\\' is not listed but that table is defined as an example only. It states in the paragraph that the valid escape sequences are defined in 7.12.1

in the abnf, charValue it documents 'Single quotes shall be escaped per 7.12.2 and  stringValue it states that Double quotes shall be escaped. For details see 7.12.1

Also, single quote is not defined as escaped and that is logical since within MOF it is just another character with no special powers.

In review I think the spec is correct or I am missing something.

Lets discuss to sort out what we see differently.

**Comment by andy-maier** [comment]
The issue is that there is no text that **requires** to escape backslashes using the escape sequence defined on line 4224 (Section 7.12.1).

So it is optional for an implementation to escape backslashes.

If an implementation decides not to escape backslashes, it runs into the problem that when parsing MOF, it is not clear whether `\\` is one escaped backslash, or two unescaped backslashes.

So the spec should better state a requirement that backslashes shall be escaped, for both string constants and char16 constants. I did not find where it states that. Line 4486 in section 8.5 states: "As defined in 7.12.1, representing a string value as a string in CIM MOF includes the escaping of any double quotes and backslashes present in the string value.". This text only references the section stating the actual requirement, and therefore cannot be considered a requirement by itself. And section 7.12.1 defines the requirement only for double quotes, and not also for backslashes.

The spec correctly states the requirement for escaping double quotes in string constants on line 4214 (section 7.12.1): "Double quotes shall be escaped.", and for escaping single quotes in char16 constants on line 4238 (section 7.12.2): "Single quotes shall be escaped.".

My proposal for an update of DSP0004 is all of the following:
* In section 7.12.1, change: "Double quotes shall be escaped." to: "Double quotes and backslashes shall be escaped.".
* In section 7.12.2, change: "Single quotes shall be escaped." to: "Single quotes and backslashes shall be escaped.".
* In section A.2, in the definition of `charValue`, change the comment: "Single quotes shall be escaped." to: "Single quotes and backslashes shall be escaped.".
* In section A.2, in the definition of `stringValue`, change the comment: "Double quotes shall be escaped." to: "Double quotes and backslashes shall be escaped.".

**Comment by andy-maier** [comment]
Another discussion point (besides the proposal above):
* Did we fix this for 0.9, to always escape all possible short sequences?

**Comment by andy-maier** [comment]
We discussed what to do with the escapable characters in the control character range (U+0008, U+0009, U+000A, U+000C, U+000D). The bottom line was we would like to see a recommendation stated to escape those, because they are non-printable. It probably cannot become a requirement because that would cause MOF to be illegal that did not escape it so far.

**Comment by andy-maier** [comment]
**Discussion:**
* Clarify how this was handled.

**Comment by KSchopmeyer** [comment]
The issue has been documented in DMTF mantis as issue 2682

**Comment by KSchopmeyer** [comment]
The remaining component of this issue is to insure in pywbem that tomof has the correct escaping and that we have tests to prove that.

**Comment by andy-maier** [comment]
I verified what the code does in terms of MOF escaping, and it turns out that there is one central function `mofstr() in c`cim_obj.py` which escapes as much as possible. There are also testcases in `testsuite/test_cim_obj.py`.

PR #714 has clarifications for the docstring of the internal `mofstr()` function.
