### ISSUE TITLE
cim_operations EnumerateInstances

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#329]
Code optionally gets namespace from ClassName parameter but documentation is unclear about this.

          ClassName (:term:`string` or :class:`~pywbem.CIMClassName`):
            Name of the class to be enumerated, in any lexical case.
            If specified as a :class:`~pywbem.CIMClassName` object, its host
            component will be ignored.

**Comment by andy-maier** [comment]
This issue actually applies to all four EnumInstance operations (ein, ei, oein, oei).

Because the description of the `namespace` argument already describes the full story for namespace defaulting, I suggest that the `ClassName` argument just clarifies that its namespace component does play a role for namespace defaulting, and otherwise refers to the `namespace` argument.

**Proposal:**

Change the text:

    If specified as a :class:`~pywbem.CIMClassName` object, its host
    component will be ignored.

To:

    If specified as a :class:`~pywbem.CIMClassName` object, its namespace
    component will be used as a default namespace as described for the
    namespace argument, and its host component will be ignored.

**Comment by andy-maier** [comment]
This proposal should be picked up by PR #320 as far as the pull operations go, but it should also be applied to `EnumerateInstances()` and `EnumerateInstanceNames()`.

**Comment by andy-maier** [comment]
PR #320 does address this.
