### ISSUE TITLE
Add class path to CIMClass

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#349]
issue #339 clarified that we have an issue with the documentation/api on association responses in that the documentation defined the return of a class but the code/api returns a tuple. 

Since this knowledge of the path of the class is important, should it actually be part of the class itself?

**Comment by andy-maier** [comment]
If we add path, we need to describe where it is used on input, and set on output.

Given that we decided not to change the class level association operator methods, we would not benefit from it by getting rid of the tuples. However, we could still set it on output, in case someone prefers to deal with the one class object that contains both.

EC and GC could also set the path in their results.

Need to look at MC.

Where else would it be used or set?

**Comment by andy-maier** [comment]
In CC and MC we need to look at the path of the provided class objects and use its namespace in the same precedence as DC does it with its path arg.

**Comment by andy-maier** [comment]
Overall, I think I have a slight preference for adding path.

**Comment by andy-maier** [comment]
We agreed to add path on both input and output, and move it to 0.10.0

**Comment by andy-maier** [comment]
**Discussion point:** If we add a path to `CIMClass`, would we change the return values of class operations that today return a tuple class, path?

These are:
* EnumerateClasses returns just a list of CIMClass objects and no class path at all. The class path is not an essential piece of information because it could be constructed by taking the class name from the returned CIMClass objects, and the input namespace. However, the namespace actually used is defaulted from 3 sources.
* GetClass returns just a CIMClass object and no class path at all. The class path provided as input is not necessarily the one that belongs to the returned CIMClass object, because the namespace actually used is defaulted from 3 sources.
* Associators and References at class level returns a list of tuples CIMClass, CIMClassName, so at least the returned path information is precise.

**Comment by KSchopmeyer** [comment]
We agreed that the best solution is to add an internal path element and live with the fact that the associators and references will duplicate this info in the tuple response.

**Comment by KSchopmeyer** [comment]
No incompatible change and add class level asociation operations.

**Comment by andy-maier** [comment]
We agreed to move this into the next release after 0.10.0.

**Comment by andy-maier** [comment]
To summarize the direction for this issue:

* Add a `path` member to `CIMClass` so that it can be self-contained wr.t. its class path.
* In `EnumerateClasses`, have the `path` set in the returned list of `CIMClass` objects. Besides general consistency, it is useful to be able to see the namespace that was actually used from the up to 3 namespaces that were passed in.
* In `GetClass`, ditto.
* In `Associators` and `References` at class level, do not change the returned tuples of `CIMClass`, `CIMClassName`, but have the `path` set in the `CIMClass` object, for consistency.
* Add new operations `AssociatorClasses` and `ReferenceClasses` that return a list of `CIMClass` objects that have their `path` set.
* Add new operations `AssociatorClassPaths` and `ReferenceClassPaths` that return a list of `CIMClassName` objects.

These are all backwards compatible changes for the caller.

**Comment by andy-maier** [comment]
We agreed in the call today on the direction stated in the previous comment.

**Comment by KSchopmeyer** [comment]
We agreed to split this issue into two components.  This issue will be restricted to the path component on the existing functions.

We will create a new issue for the new class level associator, etc. functions.

Karl will break this up ASAP.

**Comment by andy-maier** [comment]
After splitting the work, the remaining work for this issue is:

* Add a `path` member to `CIMClass` so that it can be self-contained wr.t. its class path.
* In `EnumerateClasses`, have the `path` set in the returned list of `CIMClass` objects. Besides general consistency, it is useful to be able to see the namespace that was actually used from the up to 3 namespaces that were passed in.
* In `GetClass`, ditto.
* In `Associators` and `References` at class level, do not change the returned tuples of `CIMClass`, `CIMClassName`, but have the `path` set in the `CIMClass` object, for consistency.

These are all backwards compatible changes for the caller.

**Comment by andy-maier** [comment]
The remaining work for this issue is addressed with PR #747.
