### ISSUE TITLE
DSP0200 issue: No recommended ports defined for WBEM listeners

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#453]
I am not at all sure that the default ports we use are correct.  In fact I would think they are wrong but
not sure if there were assigned default ports in specs.

**Comment by KSchopmeyer** [comment]
I set this for 0.10.0 for the moment

**Comment by KSchopmeyer** [comment]
Lets double check in dsp 0200.  There is nothing in dspo200

**Comment by KSchopmeyer** [comment]
Lets leave this one pending further investigation.

**Comment by KSchopmeyer** [comment]
We agreed to close this issue.  no change

**Comment by andy-maier** [comment]
I'd like to reopen this one, because DSP0200 in fact defines recommended ports for the WBEM server, but it does not define ports for WBEM listeners.

From DSP0200 section 7.7 "Discovery and Addressing":

===
The DMTF recommends the use of the following well-known IP ports in compliant WBEM servers. This is a recommendation and not a requirement. The DMTF has registered these port addresses with IANA, so they are for the exclusive use of the DMTF.

* CIM-XML (HTTP) 5988/tcp
* CIM-XML (HTTP) 5988/udp
* CIM-XML (HTTPS) 5989/tcp
* CIM-XML (HTTPS) 5989/udp

===

We should open a DMTF issue against DSP0200 to get recommended ports defined for WBEM listeners as well. Proposal would be to use the same port numbers as for WBEM servers.

This issue got reopened to track the creation of the DMTF issue.

**Comment by KSchopmeyer** [comment]
Created DMTF Mantis issue # 2853 on 8 Oct. 2019
