### ISSUE TITLE
Get back to a single SSL environment across Python 2 and 3

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#496]

**Comment by KSchopmeyer** [comment]
We have concluded that we may not be able get back to a single ssl.  

Karl agreed to generate an overview of the alternatives.

**Comment by andy-maier** [comment]
I think the direction should be to switch to using the "requests" package.

In addition to solving this issue here, it would speed up connections because the "request" package maintains a pool of SSL sockets, and we so far go through an entire SSL handshake for each single operation.

**Discussion point:** Do we agree on this directions, or do we want to look at more options?

**Comment by KSchopmeyer** [comment]
The two alternatives today appear to be:

1. Go to requests
2. Go completely to python ssl

Some of the open questions include:
1.. This means that anybody using the cert callback would not be getting a call back so we would have to tell them somehow. We propose that we would keep the callback but put a deprecation warning on it. that is better than removing it and causing in all probability an exception.  We need to think this one out since if someone was using the callback for real security, just not calling it means a security hole.

2. TOCTOU issues since this was the real reason that that Redhat went to m2crypto 

3. Issues in what we do with the callback in the future. It would appear that we could not remove it until pywbem 2.0

4. Is there a way we could simulate the callback with either the python ssl or requests code so that the user did have a way to inspect the server cert???

**Comment by andy-maier** [comment]
Will be addressed when migrating to the "requests" package. See issue #280. Has been addressed in PR #2023.
