### ISSUE TITLE
testsuite/compat_args.py. Is there any reason to keep this in testsuite?

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#526]
This is not really part of the test suite.  Should we move it to tools?

**Comment by andy-maier** [comment]
It tests general behavior of Python that we rely on with our compatibility.

I see 4 options:

  1. Do nothing.
  2. Declare that this compatibility is understood now and remove the script.
  3. Move the script to a `try` directory.
  4. Change it to become an official testcase, because it verifies something our compatibility relies on.

**Comment by andy-maier** [comment]
We agreed to go for option 3.

**Comment by KSchopmeyer** [comment]
We agreed to go with 3, a try directory.

**Comment by andy-maier** [comment]
Addressed in PR #584.
