### ISSUE TITLE
Flake8 warning about __all__

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#547]
cim_operations.py WARNING: `__all__` is defined as a list, this means pep257 cannot reliably detect contents of the `__all__` variable, because it can be mutated. Change `__all__` to be an (immutable) tuple, to remove this warning. Note, pep257 uses `__all__` to detect which definitions are public, to warn if public definitions are missing docstrings. If `__all__` is a (mutable) list, pep257 cannot reliably assume its contents. pep257 will proceed assuming `__all__` is not mutated.

**Comment by KSchopmeyer** [comment]
Karl to try to recreate this warning.

**Comment by KSchopmeyer** [comment]
I see is sometimes when I use flake8 without the config file but nothing consistent.

**Comment by andy-maier** [comment]
This warning is produced by `pydocstyle` (formerly called `pep257`), see [here](https://github.com/PyCQA/pydocstyle/blob/master/src/pydocstyle/parser.py#L382). It was introduced as a resolution to issue PyCQA/pydocstyle#62.

`pydocstyle` is integrated into `flake8` via the `flake8-docstrings` plugin, but it does not get installed / enabled by default when installing flake8.

I could verify that in a newly created virtual python environment (on py27), `make develop` installs `flake8` but not `flake8-docstrings`. Running flake8 via `make check` did not produce the warning.

Installing `flake8-docstrings` and re-running `make check` did produce the warning.

Please double check whether you see it only occasionally because you are running flake8 in an environment that happens to have `flake8-docstrings` installed.

**Comment by andy-maier** [comment]
Karl clarified that this happens only in the flake8 integration into the Geany editor.
Karl wants to send the geany integration to Andy.

**Comment by andy-maier** [comment]
AI for Andy: Verify issue with Geany integration.

**Comment by KSchopmeyer** [comment]
I have flake8 and pyflakes installed. I do not show a separate flake8-docstrings.   As the PyCQA/pydocstyle#62 points out, the whole thing is contentious. Note that it appears as a warning when I run flake8 within geany itself and NOT when the make file runs flake8. Futher it only occurs some times , largely when there are no other errors and when there is no.flake8 file in the directory containing the file being flaked.

I therefore propose that we close this bug as won't fix'

**Comment by andy-maier** [comment]
Closing this issue as won't fix.
