### ISSUE TITLE
pywbem 0.9.0 Windows Installation Error M2Crypto

### ISSUE THREAD

**Issue by mmumshad** [pywbem/pywbem#557]
I am trying to install pywbem 0.9.0 with pip install. It fails with the below error while trying to install M2Crypto:

```
SWIG/_m2crypto_wrap.c(6522) : fatal error C1083: Cannot open include file: 'poll.h': No such file or directory
```

**Comment by mmumshad** [comment]
Found this on M2Crypto issues. Does this mean there is no way to install pywbem 9.0 on Windows?
https://gitlab.com/m2crypto/m2crypto/issues/57

**Comment by andy-maier** [comment]
If you use pywbem with Python 3, it uses the built-in SSL support and not M2Crypto. Not sure this helps in your case, but right now I don't have any other solution. It seems like Pywbem cannot do anything there (except for moving away from M2Crypto).

**Comment by andy-maier** [comment]
Karl and I discussed this in our phone call today, and we will try out whether the Python 2 standard SSL can be used.

**Comment by andy-maier** [comment]
This will not be addressed in the upcoming 0.10.0, but we'll look into it after that.

**Comment by andy-maier** [comment]
Karl and I agreed to move it beyond 0.10.0.

**Comment by andy-maier** [comment]
The installation on Windows has been reworked as part of PR #857 (which will roll out with pywbem 0.12.0 soon), and is continually tested on the Appveyor CI since 0.11.0.

There is still a need to describe the installation of prerequisite packages for Windows inthe installation desction of the documentation. This is the remaining todo for this issue and should be done in 0.12.0.

**Comment by andy-maier** [comment]
PR #865 describes the installation of prerequisite packages for Windows in the installation section of the documentation and should address this issue.
