### ISSUE TITLE
optparse vs argparse

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#69]
At this point in the python history, optparse has been officially deprecated with argparse as its replacement.  pywbem imports optparse and masks it to look like argparse.  We should really update to argparse as the import keeping this pywbem away from deprecated packages. Hopefully this is an almost free update.

**Comment by andy-maier** [comment]
The import of `argparse` that was done as part of the Python 3 work and its subsequent use as if it were `optparse` does not work, because it is not compatible.

`argparse` seems to be available for all supported Python versions including Python 2.6. (On some distros such as CentOS 6, if the expectation is to get it as an OS-level package instead of from pyPI, it requires additional repos such as EPEL).

So it is a valuable goal to migrate to `argparse`, but that is not needed yet for 0.8.0, IMO.

**Comment by andy-maier** [comment]
PR #68 removes the incorrect use of `argparse` again and adds a ToDo to migrate to it, lateron.
