### ISSUE TITLE
Recorder does not write utf8 data in python 2.7

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#700]
In python 2.7, a simple file open will not create a file in which utf-8 characters can be written. The following error occurs

  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/_recorder.py", line 518, in record
    self._fp.write(data)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 2204: ordinal not in range(128)

Strictly this is not our issue since we assign the responsibility for file open to the user. Thus, for example, run_cim_operations must create a utf-8 writable file pointer with the open meaning that it must use something like rather than the built-in open:

    codecs.open(...)

The simplest solutions is just to document the requirement in the recorder documentation. 

The alternate is to provide a file opener in recorder.py or cim_operations.py that covers the issue.

DISCUSSION: Alternate solutions

For the moment I have put code into run_cimoperations.py and test_recorder.py to use the codecs.

**Comment by andy-maier** [comment]
The requirement for the `TestClientRecorder` constructor is indeed that the file pointer is to a "text file", i.e. one whos `write()` method takes a unicode object and encodes it using UTF-8. After all, when the data is in the file, it is always encoded Bytes.

The easiest way to open a file in text mode is not by using the `codec` package, but by using the built-in `open()` function:

    text_file = open("Output.txt", "w", encoding='utf8')

Options:
1. Document the requirement for text mode (and leave the code as is).
2. Document the requirement for text mode and add a static method for opening the file in text mode.
3. Add flexibility to the code that writes to the file so that it adjusts to the mode in which the file happens to be open, and document that the file can be opened in binary mode or in text mode.

**Comment by KSchopmeyer** [comment]
We agree that option 1 is the most logical.

**Comment by KSchopmeyer** [comment]
Lets implement 2 above.
