### ISSUE TITLE
Add new cim operation methods for class associators, references, etc.

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#712]
This was originally part of issue # 349 that defined requirement for path component for class responses and also new operations for class level associator, reference, etc. classes.

We are separating the issues.

This cannot be implemented until #349 is implemented but we propose to add the following methods to WBEMConnection to separate class level operation requests from instance level operation requests.

* Add new operations `AssociatorClasses` and `ReferenceClasses` that return a list of `CIMClass` objects that have their `path` set.
* Add new operations `AssociatorClassPaths` and `ReferenceClassPaths` that return a list of `CIMClassName` objects.

These are all backwards compatible changes for the caller.

**Comment by andy-maier** [comment]
In our meeting on 2018-04-11, we stated that we would seriously consider not implementing such operations. Class-level association traversals are rarely used, and the existing association operations solve that problem reasonably. Spending effort for a slightly nicer because more canonical client-side API does not seem to be worth the effort.

**Discussion point:** Make decision to close this issue as won't fix.

**Comment by KSchopmeyer** [comment]
I agree that this one is too little too late.  Lets close it as will not do.
