### ISSUE TITLE
Issues with use_pull_operations attribute

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#782]
The description of the `use_pull_operations` instance attribute of `WBEMConnection` states:

* Indicates whether the client will attempt the use of pull operations in any Iter…() methods. However, each operation has its own internal equivalent flag based on this flag to allow for WBEM servers that implement only some of the pull operations.
  This variable is initially set from the same-named input argument. If it is initially None, it is modified when Iter…() methods are invoked, dependent on the support for pull operations in the WBEM server.

  After the first call , the variable will be either True or False and indicating whether pull operations will be used in this and subsequent Iter…() methods.
  **Update:** On the last statement: This applies to the non-public instance attributes for each operation type, but not to the `use_pull_operations` instance attribute.

Looking at the code, there are these issues:
* This instance variable is not changed as the connection learns about supported pull operations.
* It is writeable because it is simply a public instance attribute, but writing to it has no effect.

We need to discuss what we want to do with this variable, as long as the Iter...() methods are still experimental:
* Do we want an indication of what was learned?
* Do we want the users to be able to reset the automatic detection behavior?
* Do we want the users to be able to change the preference once the connection object exists?

**Comment by KSchopmeyer** [comment]
1. Do we want an indication of what was learned.?
I never intended that this variable serve as updatable indication of success or failures.  We added the detailed variables for each request type because some implementations may not have fully implemented pull. However, I had thought that this was always to be a variable that controlled intention, not results.
2. Do we want users to be able to reset automatic detection behavior?
I think not.  They asked for a particular behavior. We use that behavior pattern for that connection. If we change it after the first error  I think it could get messy because that may be behavior for one operation, not overall.
3. Do we want users to be able to change preference once object exists?
My first thought is that they create new connection.

Note: I am still thinking this through now and have not had time to go through all of the possible cases to see if allowing changes would cause more problems or fewer.

**Comment by andy-maier** [comment]
After discussion:
* We think it is not wirthwhile to provide the ability to reset or modify the approach on an existing connection.
* Because updating the `use_pull_operations` instance attribute does ot do anything, that attribute should become a read-only property.
* The description of the `use_pull_operations` instance attribute should make it clear that this reflects the input argument, i.e. the intent, and not the actual state.
* The only open item is: Do we want to make the actual state (by operation) accessible. If we do, then we would change the current private instance attributes for each operation into read-only public properties.

**Comment by andy-maier** [comment]
PR #881 addresses the items listed in the previous comment, except for the last one which is to be discussed.

**Comment by KSchopmeyer** [comment]
We agreed to not make the detailed pull state available for this release. We can always change this in the future.

**Comment by andy-maier** [comment]
With that, PR #881 fixes the issue.
