### ISSUE TITLE
clobber does not remove the mof-schema directory

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#82]
Not sure what is correct but I noted that the make clobber does not remove the schema directory in test_schema and this is (at least today) a transient directory.  I only noted it after I made an error in changing the name mofurl to MOF_URL and realizing that I had not done it in all places when the pull request failed.

We should decide if clobber should remove this directory but it is low priority

**Comment by andy-maier** [comment]
I had the removal in, and removed it again in order to save downloads from dmtf.

 if we check the schema mof files in, we would solve the frequent download issue, and in addition could track changes to the schema.

By the way, the experimental schema has many more elements than final, and tests new things earlier, that's why I used it. I think it also is run through some formal test, no?

**Comment by KSchopmeyer** [comment]
Note that the real issue may be that when we increase the version of the model, we have to manually remove the old schema and to replace it.

Maybe we should go back to the experimental assuming it does compile.

**Comment by andy-maier** [comment]
The discussion on the call today was that this should be solved after it is clear how we deal with the many downloads of the CIM schema in Travis CI runs (issue #49).

**Comment by andy-maier** [comment]
This has become obsolete now that we have the schema zip file in the repo. Closing it.
