### ISSUE TITLE
run_cim_operation includes tests that should be elsewhere

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#90]
This is supposed to be a test against a server but it includes a test group called internal_tests.  I think that internal tests (which does not require a server) should be put somewhere else.  Since right now that test (the only test is for utf characters) is broken in that it fails with python 3, this is a good time to move it.

**Comment by andy-maier** [comment]
I agree that  `Test_check_utf8_xml_chars()` should be moved into a testcase file that runs automatically. The `run_cim_operation.py` file was once called `test_cim_operation.py` and was renamed so that it does not run automatically (because most of its functions need a real WBEM server). The `Test_check_utf8_xml_chars()` function was apparently overlooked in that rename. I suggest that it is moved into a new `test_cim_operation.py` file.

In addition, the `tests` list is not used at all, I believe it is a remainder from using `comfychair`. Instead of removing, it would be good to display the possible testcase names in the help text, maybe in a separate `--help-tc` option.

**Comment by KSchopmeyer** [comment]
Agreed. I really could not make sense of the tests thing so tks for explanation.

**Comment by andy-maier** [comment]
Resolved with PR #92.
