### ISSUE TITLE
Many of the cim objects have only partial _repr_ implementations

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#93]
Many _repr_ implementations only represent the first few components of the object and ignore the
remainder.  This makes it difficult to use this for diagnostics, etc.

**Comment by andy-maier** [comment]
The PR #127 addresses this issue, but it also changes `str()` on a number of CIM object classes.
A particular discussion point is backwards compatibility. Basically, we are assuming thet the return value of `repr()` can be changed because a client should not rely on its format. For the changed `str()` functions, we also assume that, and that is probably ok, because they were previously equal to `repr()`. Except for the three mentioned changes, their return value is unchanged compared to before this PR.
