### ISSUE TITLE
test_cim_operations.py check_utf8 fails the error tests in python3.

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#94]
This does not show up in testing because that code bypassed for python 3 to get the new file into the build.

**Comment by andy-maier** [comment]
The root cause was that in Python 3, iterating through a byte string (type bytes) gets int numbers, instead of single-character byte strings. See http://stackoverflow.com/questions/14267452/iterate-over-individual-bytes-in-python3

Because what is actually needed in the code, is the integer, I fixed this by version-specific code, that in Python 3 directly uses the integer-typed loop object, and that in Python 2 converts the single-byte `str` object to an integer using `ord()`.
