### ISSUE TITLE
in virtualenv when I move to python2 env that already has pkgs installed setup forces sudo

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#95]
When I move between python3 and python2.7 envs, each time I go back to 2.7 it requires that i input
the sudo password.  This happens when I do make clobber && make all. This happens to
karl but not to Andy.

**Comment by andy-maier** [comment]
Karl, I was able to reproduce it and I believe I found the root cause.
There is a method `OSInstaller.authorized()` that when on Linux, issues a `sudo echo ok` command to find out whether the current user is authorized for sudo. It does that for every check for an OS-level package, even if it is up to date. On the first time, sudo asks for the password. Then, on subsequent invocations, it is happy because it seems to cache the password. After some time, it asks again. That's why it may seem that it has to do with `make clobber` or with switching between Python versions. I think it just has to do with elapsed time.
